import {beforeEach,describe,expect,it,vi} from "vitest";
const state=vi.hoisted(()=>({invoke:vi.fn(),enqueue:vi.fn(),revision:"current",previous:null as null|Record<string,unknown>,runner:null as null|((...args:any[])=>Promise<any>),reserve:vi.fn(),release:vi.fn(),setResult:vi.fn(),stop:false}));
vi.mock("@tauri-apps/api/core",()=>({invoke:state.invoke}));
vi.mock("./controlMedia",()=>({listControlAssets:()=>[{id:"source",path:"p/original.mp4",kind:"video",target:{kind:"cut",id:"cut"}},{id:"other",path:"p/other.mp4",kind:"video",target:{kind:"cut",id:"other-cut"}},{id:"image",path:"p/image.png",kind:"image",target:{kind:"cut",id:"cut"}}],controlMediaTarget:()=>({stem:"컷_1",ownerName:"장면",assetType:"scene-cut"})}));
vi.mock("./projectWrite",()=>({readProject:()=>({title:"QA"})}));
vi.mock("./projectControl",()=>({getProjectSnapshot:async()=>({revision:state.revision}),ProjectControlError:class extends Error{constructor(public code:string,message:string){super(message);}}}));
vi.mock("./localProjectStore",()=>({projectFolderName:()=>"QA"}));
vi.mock("./mediaLibrary",()=>({saveProjectMediaAsset:state.reserve,releaseEmptyProjectAsset:state.release,safeFileName:(s:string)=>s}));
vi.mock("./taskQueue",()=>({enqueueTaskOperation:state.enqueue,registerTaskRunner:(_kind:string,run:any)=>{state.runner=run;},isStopping:()=>state.stop,setTaskResult:state.setResult,getTaskByOperationId:()=>state.previous,whenTaskJournalReady:async()=>{}}));
import {mediaEditSchema,validateMediaEdit,enqueueMediaEdit,probeMediaEdit} from "./controlMediaEdit";
const clip={kind:"clip" as const,sourceVideoAssetId:"source",sourceCutId:"cut",sourceSha256:"1".repeat(64),sourceFrames:33,startFrame:0,endFrameExclusive:33};
const hold={kind:"hold" as const,sourceVideoAssetId:"source",sourceCutId:"cut",sourceSha256:"1".repeat(64),sourceFrames:33,frame:32,frames:143,frameRgbSha256:"2".repeat(64),reviewDeclaration:"explicitly-reviewed-frame" as const};
const base={projectId:"p",expectedRevision:"current",operationId:"edit-qa",target:{kind:"cut" as const,id:"cut"},width:1024,height:576,fps:{numerator:16,denominator:1},segments:[clip,hold],expectedOutputFrames:176,audioPolicy:"omit" as const};
beforeEach(()=>{state.invoke.mockReset().mockResolvedValue({ready:true,blockers:[]});state.enqueue.mockReset().mockResolvedValue({jobId:"cpu-job"});state.reserve.mockReset().mockResolvedValue({path:"p/derived.mp4"});state.release.mockReset().mockResolvedValue(undefined);state.setResult.mockReset();state.revision="current";state.previous=null;state.stop=false;});
describe("원본 보존 구간 편집",()=>{
  it("33+143을 독립 CPU 큐에 명시해 보낸다",async()=>{expect(()=>validateMediaEdit(mediaEditSchema.parse(base))).not.toThrow();await expect(enqueueMediaEdit(base)).resolves.toEqual({jobId:"cpu-job"});expect(state.enqueue).toHaveBeenCalledWith(expect.objectContaining({lane:"cpu",kind:"control.media-edit",payload:mediaEditSchema.parse(base)}));});
  it("반복 호출은 같은 작업을 사용하고 새 입력은 충돌한다",async()=>{state.previous={kind:"control.media-edit",payload:mediaEditSchema.parse(base),projectId:"p",projectTitle:"QA",label:"편집"};state.revision="later";await enqueueMediaEdit(base);expect(state.invoke).not.toHaveBeenCalled();await expect(enqueueMediaEdit({...base,audioPolicy:"clip-and-silence"})).rejects.toThrow("operation_conflict");});
  it("최신 revision과 원본 컷 연결을 다시 검사한다",async()=>{state.revision="new";await expect(enqueueMediaEdit(base)).rejects.toThrow("revision");state.revision="current";await expect(enqueueMediaEdit({...base,segments:[{...clip,sourceCutId:"other-cut"}],expectedOutputFrames:33})).rejects.toThrow("association");await expect(enqueueMediaEdit({...base,segments:[{...clip,sourceVideoAssetId:"image"}],expectedOutputFrames:33})).rejects.toThrow("association");});
  it("환경 미준비와 경로 주입을 거절한다",async()=>{state.invoke.mockResolvedValue({ready:false,blockers:["missing_ffmpeg"]});await expect(enqueueMediaEdit(base)).rejects.toThrow("not_ready");for(const key of ["sourceVideo","ffmpeg","python","makePrimary","prompt"])expect(mediaEditSchema.safeParse({...base,[key]:"unsafe"}).success).toBe(false);});
  it("임의 프레임 홀드·루프·역순·길이 불일치를 거절한다",()=>{
    for(const segments of [[{...hold,frame:31}], [clip,{...hold,frame:31}], [clip,clip], [clip,{...clip,sourceVideoAssetId:"alias-id"}], [{...clip,startFrame:10,endFrameExclusive:4}]])expect(()=>validateMediaEdit(mediaEditSchema.parse({...base,segments}))).toThrow();
    expect(()=>validateMediaEdit(mediaEditSchema.parse({...base,expectedOutputFrames:175}))).toThrow("frames_mismatch");expect(mediaEditSchema.safeParse({...base,segments:[clip,{...hold,reviewDeclaration:undefined}]}).success).toBe(false);
  });
  it("probe는 실제 자산 경로와 컷을 해석하되 청정 배경 판정을 만들지 않는다",async()=>{state.invoke.mockResolvedValue({sourceSha256:"1".repeat(64),frames:33,qualityApproved:false});const result=await probeMediaEdit({projectId:"p",sourceVideoAssetId:"source",sourceCutId:"cut",selectedFrames:[32]});expect(result.revision).toBe("current");expect(result.qualityApproved).toBe(false);expect(state.invoke).toHaveBeenCalledWith("media_edit_probe",{request:{operation:"probe",sourceVideo:"p/original.mp4",selectedFrames:[32]}});});
  it("probe 도중 바뀐 프로젝트 revision을 오래된 자산 검증으로 통과시키지 않는다",async()=>{state.invoke.mockImplementation(async()=>{state.revision="changed";return {frames:33};});await expect(probeMediaEdit({projectId:"p",sourceVideoAssetId:"source",sourceCutId:"cut",selectedFrames:[32]})).rejects.toThrow("검사 중 프로젝트가 바뀌었습니다");});
  it("작업자는 원본 대신 다른 파생명과 기존 미디어 저장 서비스를 사용한다",async()=>{state.invoke.mockResolvedValue({output:"p/derived_001.mp4",meta:{qualityApproved:false}});const result=await state.runner!(mediaEditSchema.parse(base),()=>{}, {id:"cpu-job"});expect(state.reserve).toHaveBeenCalledWith(expect.any(File),expect.objectContaining({assetType:"scene-video",stem:"컷_1_구간편집"}));expect(state.invoke).toHaveBeenCalledWith("media_edit_run",expect.objectContaining({request:expect.objectContaining({segments:[{...clip,sourceVideo:"p/original.mp4"},{...hold,sourceVideo:"p/original.mp4"}]})}));expect(result.data).toMatchObject({attached:false,registrationRequired:true,registrationTool:"media_register",registrationMakePrimary:false,primaryChanged:false,qualityApproved:false});expect(state.release).toHaveBeenCalled();});
  it("취소·실행 전 revision 충돌은 파생 파일 쓰기 전에 멈춘다",async()=>{state.stop=true;await state.runner!(mediaEditSchema.parse(base),()=>{}, {id:"cpu-job"});expect(state.reserve).not.toHaveBeenCalled();state.stop=false;state.revision="later";await expect(state.runner!(mediaEditSchema.parse(base),()=>{}, {id:"cpu-job"})).rejects.toThrow("revision");expect(state.reserve).not.toHaveBeenCalled();});
});

describe("음원 보존 기본값",()=>{it("생략하면 보존하고 명시적인 omit만 무음 처리한다",()=>{const {audioPolicy,...input}=base;expect(mediaEditSchema.parse(input).audioPolicy).toBe("clip-and-silence");expect(mediaEditSchema.parse(base).audioPolicy).toBe("omit");});});
