import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
const state=vi.hoisted(()=>({invoke:vi.fn(),listen:vi.fn(),enqueue:vi.fn(),stop:false,unlisten:vi.fn(),runner:undefined as undefined|((raw:unknown,report:ReturnType<typeof vi.fn>,task:{id:string})=>Promise<unknown>)}));
vi.mock("@tauri-apps/api/core",()=>({invoke:state.invoke}));vi.mock("@tauri-apps/api/event",()=>({listen:state.listen}));
vi.mock("./taskQueue",()=>({enqueueTaskOperation:state.enqueue,isStopping:()=>state.stop,registerTaskRunner:(_:string,r:typeof state.runner)=>{state.runner=r;}}));
const input={operationId:"native-1",engine:"ltx25",repo:"Lightricks/LTX-2.5",component:"transformer"};
beforeEach(()=>{vi.resetModules();vi.resetAllMocks();state.stop=false;state.listen.mockResolvedValue(state.unlisten);});afterEach(()=>vi.useRealTimers());
describe("native model download control",()=>{
    it("rejects arbitrary paths, LoRA, tokens and engines before enqueue",async()=>{const api=await import("./controlModelDownload");for(const changed of [{component:"lora"},{component:"../secret"},{repo:"evil/repo"},{engine:"wanvideo"},{token:"secret"},{url:"https://evil"},{operationId:" "}])await expect(api.enqueueControlModelDownload({...input,...changed})).rejects.toThrow();expect(state.enqueue).not.toHaveBeenCalled();});
    it("uses a separate download lane and persisted operation ID",async()=>{const api=await import("./controlModelDownload");await api.enqueueControlModelDownload(input);expect(state.enqueue).toHaveBeenCalledWith(expect.objectContaining({lane:"download",operationId:input.operationId,payload:input}));});
    it("routes only own transfer progress and does not claim generation ready",async()=>{await import("./controlModelDownload");state.invoke.mockResolvedValue({sha256:"a".repeat(64),nativeContractVerified:false});const report=vi.fn();const result=await state.runner!(input,report,{id:"mine"});const callback=state.listen.mock.calls[0][1];callback({payload:{transferId:"other",component:"transformer",percent:75}});expect(report).not.toHaveBeenCalled();callback({payload:{transferId:"mine",component:"transformer",percent:75}});expect(report).toHaveBeenCalledWith(expect.objectContaining({progress:.75}));expect(result).toEqual({data:{sha256:"a".repeat(64),nativeContractVerified:false,modelInstalled:false,generationEnabled:false}});expect(state.unlisten).toHaveBeenCalledOnce();});
    it("cancels only own transfer while network is stalled and cleans listeners",async()=>{vi.useFakeTimers();await import("./controlModelDownload");let reject!:(e:Error)=>void;state.invoke.mockImplementation((name:string)=>name==="model_component_download"?new Promise((_,fail)=>{reject=fail;}):Promise.resolve(true));const pending=state.runner!(input,vi.fn(),{id:"mine"});const outcome=expect(pending).rejects.toThrow("cancelled");await vi.advanceTimersByTimeAsync(0);state.stop=true;await vi.advanceTimersByTimeAsync(200);expect(state.invoke).toHaveBeenCalledWith("model_component_download_cancel",{transferId:"mine"});reject(new Error("cancelled"));await outcome;expect(state.unlisten).toHaveBeenCalledOnce();expect(vi.getTimerCount()).toBe(0);});
    it("propagates access rejection without retry or success",async()=>{await import("./controlModelDownload");state.invoke.mockRejectedValue(new Error("HTTP 403"));await expect(state.runner!(input,vi.fn(),{id:"mine"})).rejects.toThrow("HTTP 403");expect(state.invoke).toHaveBeenCalledOnce();expect(state.unlisten).toHaveBeenCalledOnce();});
    it("bounded inspection has no operation queue or extra input",async()=>{const api=await import("./controlModelDownload");await api.inspectControlModel({engine:input.engine,repo:input.repo,component:input.component});expect(state.invoke).toHaveBeenCalledWith("model_component_inspect",{engine:input.engine,repo:input.repo,component:input.component});expect(state.enqueue).not.toHaveBeenCalled();await expect(api.inspectControlModel({...input})).rejects.toThrow();});
});
