import {describe,expect,it,vi} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readEditableApiGraph,editableWorkflowFields,newWorkflowEditorDraft,normalizeWorkflowEditorDraft,fixedWorkflowReferenceGroups} from './workflowEditor';
import {applyWorkflowVoiceOptions,voiceWorkflowSupport} from './workflowVoiceOptions';
import {workflowTaskReceipt} from './workflowTaskReceipt';
import type {QueueTask} from './taskQueue';
import type {WorkflowSelection} from './comfyWorkflowContract';
vi.mock('./i18n',()=>({useT:()=>((value:string)=>value)}));
vi.mock('./mediaLibrary',()=>({revealFile:vi.fn(),registerMirrorSection:vi.fn()}));
vi.mock('./localOutput',()=>({runLocalToProject:vi.fn()}));
import ComfyTaskReceipt from '../components/ComfyTaskReceipt';
const graph={one:{class_type:'Loader',inputs:{model:'existing.safetensors',api_key:'PRIVATE'}},two:{class_type:'Loader',inputs:{model:'second.safetensors'}},text:{class_type:'Text',inputs:{text:'manual'}},save:{class_type:'Save',inputs:{prefix:'cpu'}}};
const selection=():WorkflowSelection=>({slots:[{id:'text',nodeId:'text',input:'text',semantic:'text',required:true},{id:'language',nodeId:'text',input:'language',semantic:'language',required:false},{id:'profile',nodeId:'text',input:'instruction',semantic:'voiceProfile',required:false},{id:'speaker',nodeId:'text',input:'speaker',semantic:'value',required:false},{id:'model',nodeId:'text',input:'model',semantic:'value',required:false}],promptRoles:[{id:'voice',modelRuleId:'qwentts',loaderNodeIds:['one'],positiveSlotIds:['text'],negativeSlotIds:[],negativeSupport:'unsupported'}],selectedPromptRoleId:'voice',outputNodeIds:['save'],referenceGroups:[]});
describe('API 역할 편집·지원 옵션·작업 결과 표시 CPU',()=>{
 it.each(['{}','[]','{"nodes":[],"links":[]}','{"one":{"class_type":"X"}}'])('잘못된 API graph는 편집기로 자동 변환하지 않는다: %s',text=>{expect(()=>readEditableApiGraph(text)).toThrow();});
 it('복수 loader와 비밀값을 자동 선택·노출하지 않고 모델 역할이 비어 있는 초안을 만든다',()=>{const text=JSON.stringify(graph),draft=newWorkflowEditorDraft(text,'C:/chosen.json');expect(draft.selection.promptRoles).toEqual([]);expect(draft.source.modelIds).toEqual([]);expect(draft.selection.selectedPromptRoleId).toBe('');expect(()=>normalizeWorkflowEditorDraft(draft)).toThrow();expect(editableWorkflowFields(readEditableApiGraph(text)).map(field=>field.input)).not.toContain('api_key');expect(JSON.stringify(editableWorkflowFields(graph))).not.toContain('PRIVATE');});
 it('선택된 역할의 모델을 편집하면 source의 모델 정보도 명시 역할에 맞춰 갱신한다',()=>{const draft=newWorkflowEditorDraft(JSON.stringify(graph),'C:/chosen.json');draft.source.outputKind='audio';draft.source.operation='tts';draft.selection=selection();draft.selection.promptRoles[0].modelRuleId='other-voice';const normalized=normalizeWorkflowEditorDraft(draft);expect(normalized.source.promptProfile).toBe('other-voice');expect(normalized.source.modelIds).toEqual(['other-voice']);expect(normalized.selection.promptRoles[0].loaderNodeIds).toEqual(['one']);});
 it('image/video/audio 참조를 의미별 fixed 그룹으로 분리하며 중복 슬롯을 추가하지 않는다',()=>{const s=selection();s.slots=['identityImage','sourceVideo','voiceReference','identityImage','cameraGuide'].map((semantic,i)=>({id:'s'+i,nodeId:'n'+i,input:'file',semantic:semantic as any,required:true}));const groups=fixedWorkflowReferenceGroups(s);expect(groups.map(group=>[group.role,group.mediaKind,group.slotIds])).toEqual([['identityImage','image',['s0','s3']],['sourceVideo','video',['s1']],['voiceReference','audio',['s2']],['cameraGuide','video',['s4']]]);expect(groups[0]).toMatchObject({minItems:2,maxItems:2,identity:'multiple'});s.referenceGroups=groups;expect(fixedWorkflowReferenceGroups(s)).toEqual([]);});
 it('음성 언어·화자·모델 옵션과 연기 특징을 각 검토 의미 슬롯에 전달한다',()=>{const contract={selection:selection(),voiceOptionBindings:{model:'model',speaker:'speaker',actingProfile:'profile'}};const values=applyWorkflowVoiceOptions(contract,{model:'design',speaker:'Sohee',language:'Korean',category:'idol',gender:'female',ageRange:'twenties',traits:'낮고 부드러움'},{});expect(values).toMatchObject({model:'design',speaker:'Sohee',language:'Korean',profile:expect.stringContaining('낮고 부드러움')});expect(values.profile).toContain('노래하지 말고');expect(voiceWorkflowSupport(contract).size).toBe(7);});
 it('미지원 옵션·잘못된 바인딩·직접 값 충돌을 무시하지 않는다',()=>{const contract={selection:selection()};expect(()=>applyWorkflowVoiceOptions(contract,{speaker:'Sohee'},{})).toThrow('unsupported');expect(()=>applyWorkflowVoiceOptions(contract,{language:'English'},{language:'Korean'})).toThrow('conflict');expect(()=>voiceWorkflowSupport({...contract,voiceOptionBindings:{speaker:'text'}})).toThrow('binding_invalid');});
 it('등록부 실패·중지·불명 제출의 영수증은 실제 promptId와 파일을 보존하고 비밀 payload를 표시하지 않는다',()=>{const task={id:'t',kind:'cutImage',status:'failed',error:'CPU disk full',cancelRequestedAt:1,payload:{workflowPayload:{workflowSha256:'a'.repeat(64),baseUrl:'http://127.0.0.1:8190',input:{workflowTarget:{workflowId:'chosen',roleId:'main',modelRuleId:'flux2'},prompt:'PRIVATE'}}},externalCheckpoint:{provider:'comfyui',phase:'collected',promptId:'cpu-1',files:[{path:'D:\\CPU\\result.png'}]},result:{paths:['D:\\CPU\\result.png'],data:{attached:false}}} as unknown as QueueTask;expect(workflowTaskReceipt(task)).toMatchObject({promptId:'cpu-1',paths:['D:\\CPU\\result.png'],registration:'collected-unregistered',cancelled:true});const rendered=renderToStaticMarkup(createElement(ComfyTaskReceipt,{task}));expect(rendered).toContain('cpu-1');expect(rendered).toContain('등록 미확인');expect(rendered).toContain('수집 폴더 열기');expect(rendered).toContain('CPU disk full');expect(rendered).not.toContain('PRIVATE');expect(workflowTaskReceipt({...task,externalCheckpoint:{provider:'comfyui',phase:'submitting'},result:undefined})?.resubmissionBlocked).toBe(true);});
 it('정상 등록·재접속·상대 파일 경로를 서로 구별한다',()=>{const task={kind:'comfy-workflow-generate',payload:{},status:'done',result:{paths:['result.png'],data:{promptId:'cpu-2',attached:true}},externalCheckpoint:{provider:'comfyui',phase:'submitted',promptId:'cpu-2'}} as unknown as QueueTask;expect(workflowTaskReceipt(task)).toMatchObject({registration:'registered',folder:undefined,promptId:'cpu-2'});expect(renderToStaticMarkup(createElement(ComfyTaskReceipt,{task}))).toContain('기존 promptId로');});
});

import {offlineWorkflowCandidates,offlineWorkflowDraft} from './offlineWorkflowCatalog';
it('오프라인 27개는 실행 허용·환경·허가를 가져오지 않고 정확 fixed 역할 초안만 돌려준다',()=>{expect(offlineWorkflowCandidates).toHaveLength(27);expect(offlineWorkflowCandidates.every(candidate=>candidate.executionSelectable===false&&candidate.actualGenerationRegistration==='not-run'&&candidate.blockers.length>0)).toBe(true);const picked=offlineWorkflowDraft('h3-ref2va-2-identity','C:/chosen-api.json','trusted-project');expect(picked.draft.source.workflowId).toBe('h3-ref2va-2-identity-trusted-project');expect(picked.draft.source.workflowPath).toBe('C:/chosen-api.json');expect(picked.expectedGraphSha256).toMatch(/^[a-f0-9]{64}$/);expect(picked.draft).not.toHaveProperty('environment');expect(picked.draft).not.toHaveProperty('weightAuthorizations');expect(picked.draft).not.toHaveProperty('manifest');});
