import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {createElement} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {beforeEach,expect,it,vi} from "vitest";
import type {WorkflowGraph,WorkflowSelection,WorkflowSource} from "./comfyWorkflowContract";
const state=vi.hoisted(()=>({native:vi.fn(),mirror:vi.fn(),sections:new Map<string,{read:()=>unknown;write:(value:unknown)=>void}>(),graphs:new Map<string,string>(),chooser:null as {path:string;contents:string}|null,catalog:{} as Record<string,any>,snapshotError:false}));
vi.mock("@tauri-apps/api/core",()=>({invoke:state.native}));
vi.mock("./mediaLibrary",()=>({registerMirrorSection:(name:string,section:any)=>state.sections.set(name,section),queueMirrorWriteAndConfirm:state.mirror,queueMirrorWrite:vi.fn(),getMediaLibrarySettings:()=>({baseDirectory:"C:/cpu-project"})}));
vi.mock("./comfyGeneration",()=>({getComfyGenerationSettings:()=>({baseUrl:"http://127.0.0.1:8190"})}));
vi.mock("./localProjectStore",()=>({listLocalProjects:()=>[{id:"cpu-project",folder:"CPU",title:"CPU"}]}));
vi.mock("./bgmProjects",()=>({loadBgmProjects:()=>[]}));
vi.mock("./projectWrite",()=>({readProject:(id:string)=>id==="cpu-project"?{id,title:"CPU"}:null}));
vi.mock("./i18n",()=>({useT:()=>((s:string)=>s),t:(s:string)=>s}));
import {STANDARD_WORKFLOW_SOURCE_PINS,workflowSha256} from "./comfyWorkflowInspection";
import {listWorkflowLibrary,inspectAndRegisterWorkflow,workflowEntryForTarget,workflowPromptContext} from "./comfyWorkflowLibrary";
import {parseWorkflowRegistrationFile,parseWorkflowImportFile,chooseWorkflowRegistrationFile,readWorkflowIndexRegistration} from "./workflowFileImport";
import {migrateWorkflowSelectionV1ToV2} from "./comfyWorkflowInspectionV2";
import {offlineWorkflowV2Draft} from "./offlineWorkflowV2Draft";
import WorkflowPromptSelect from "../components/WorkflowPromptSelect";
import WorkflowRoleEditor from "../components/WorkflowRoleEditor";
import BatchToolsField from "../components/project/BatchToolsField";
import ComfyGenerateButton from "../components/ComfyGenerateButton";
import {newProjectDraft} from "./projectTypes";
vi.mock("./batchRun",()=>({enginesOf:(draft:any)=>draft.batchEngines??{image:"magnific",video:"magnific"},aspectOf:()=>"16:9"}));
vi.mock("./localEngines",async(importOriginal)=>({...await importOriginal<typeof import("./localEngines")>(),availableLocalEngines:()=>[],useLocalEngines:()=>{}}));
vi.mock("./magnificMcp",()=>({useMagnificStatus:()=>({connected:false})}));
vi.mock("./magnificModels",()=>({useMagnificModels:()=>[]}));
vi.mock("./llm",()=>({isDesktopApp:()=>true}));
vi.mock("./taskQueue",()=>({useTaskQueue:()=>[],registerTaskRunner:()=>{}}));

const KEY="ai-video-storage.comfy-workflow-library.v1";
beforeEach(()=>{
 vi.clearAllMocks();state.snapshotError=false;state.chooser=null;state.graphs.clear();state.mirror.mockResolvedValue(undefined);
 const data=new Map<string,string>(),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)};
 vi.stubGlobal("window",{localStorage:storage});vi.stubGlobal("localStorage",storage);
 state.catalog=JSON.parse(readFileSync(resolve("client/src/lib/__fixtures__/workflow-node-schemas.json"),"utf8"));
 state.catalog.UNETLoader.input.required.unet_name=[["cpu-model.safetensors"]];state.catalog.CLIPLoader.input.required.clip_name=[["cpu-clip.safetensors"]];state.catalog.VAELoader.input.required.vae_name=[["cpu-vae.safetensors"]];
 state.native.mockImplementation(async(command:string,args:any)=>{
  if(command==="choose_text_file")return state.chooser;
  if(command==="comfy_workflow_read_library_entry")return state.graphs.get(`${args.root}/${args.relativePath}`);
  if(command==="comfy_workflow_preflight"){const text=state.graphs.get(args.workflowPath)!;return {text,sha256:await workflowSha256(text),systemStats:{system:{comfyui_version:"0.36.0",python_version:"3.13.12",pytorch_version:"2.12.1+cu130"}},catalog:state.catalog,coreCommit:"ee71d5c4993f29086b27fde1629a945ae48425bf",nodeSourceHashes:STANDARD_WORKFLOW_SOURCE_PINS,sourceEvidence:"reported-commit-matches-disk",supportedWorkflowContractVersions:[1,2],verifiedWeights:[...["cpu-model.safetensors","cpu-clip.safetensors","cpu-vae.safetensors"].map((name,i)=>({name,category:["diffusion_models","text_encoders","vae"][i],sha256:"a".repeat(64),license:"allowed"}))]};}
  if(command==="comfy_workflow_store_revision"){if(state.snapshotError)throw new Error("CPU snapshot source changed");const snapshotPath=`C:/cpu-project/snapshots/${args.revisionId}.api.json`,text=state.graphs.get(args.workflowPath)!;if(await workflowSha256(text)!==args.expectedSha256)throw new Error("CPU snapshot source changed");state.graphs.set(snapshotPath,text);return {snapshotPath,sha256:args.expectedSha256,revisionId:args.revisionId};}
  throw new Error(`CPU unexpected native operation: ${command}`);
 });
});
function fixture(id="imported",refs=false){
 const graph:WorkflowGraph={"1":{class_type:"UNETLoader",inputs:{unet_name:"cpu-model.safetensors",weight_dtype:"default"}},"2":{class_type:"CLIPLoader",inputs:{clip_name:"cpu-clip.safetensors",type:"wan"}},"3":{class_type:"VAELoader",inputs:{vae_name:"cpu-vae.safetensors"}},"4":{class_type:"CLIPTextEncode",inputs:{clip:["2",0],text:"CPU only"}},"5":{class_type:"CLIPTextEncode",inputs:{clip:["2",0],text:""}},"6":{class_type:"EmptyLatentImage",inputs:{width:256,height:256,batch_size:1}},"7":{class_type:"KSampler",inputs:{model:["1",0],positive:["4",0],negative:["5",0],latent_image:["6",0],seed:1,steps:2,cfg:4,sampler_name:"euler",scheduler:"normal",denoise:1}},"8":{class_type:"VAEDecode",inputs:{samples:["7",0],vae:["3",0]}},"9":{class_type:"SaveImage",inputs:{images:["8",0],filename_prefix:"cpu/test"}}};
 const selection:WorkflowSelection={slots:[{id:"positive",semantic:"positive",nodeId:"4",input:"text",required:true},{id:"negative",semantic:"negative",nodeId:"5",input:"text",required:true},{id:"seed",semantic:"seed",nodeId:"7",input:"seed",required:true,defaultValue:1}],promptRoles:[{id:"main",modelRuleId:"flux2",loaderNodeIds:["1"],positiveSlotIds:["positive"],negativeSlotIds:["negative"],negativeSupport:"supported"}],selectedPromptRoleId:"main",outputNodeIds:["9"],referenceGroups:[]};
 if(refs){graph["10"]={class_type:"LoadImage",inputs:{image:"cpu.png"}};graph["11"]={class_type:"ImageCompositeMasked",inputs:{destination:["8",0],source:["10",0],x:0,y:0,resize_source:false}};graph["9"].inputs.images=["11",0];selection.slots.push({id:"reference",semantic:"sourceImage",nodeId:"10",input:"image",required:true});selection.referenceGroups=[{id:"source",role:"sourceImage",mediaKind:"image",minItems:1,maxItems:1,slotIds:["reference"],strategy:"fixed-slots",order:"explicit",identity:"none"}];}
 const source:WorkflowSource={workflowId:id,workflowPath:`C:/cpu-project/${id}.api.json`,title:"동일 표시 이름",sourceVersion:"CPU fixture only",modelIds:["flux2"],promptProfile:"flux2",outputKind:"image",operation:"text-to-image",limitations:["합성 CPU graph이며 실제 모델 생성 검증이 아닙니다."],evidence:[]};
 state.graphs.set(source.workflowPath,JSON.stringify(graph));return {source,selection,graph};
}
const register=(f:ReturnType<typeof fixture>,selectionEnvelope?:Awaited<ReturnType<typeof migrateWorkflowSelectionV1ToV2>>)=>inspectAndRegisterWorkflow({source:f.source,selection:f.selection,selectionEnvelope,projectId:"cpu-project"});

it("등록 entry 파일은 권한·manifest를 채택하지 않고 명시 역할을 가져옵니다",()=>{const f=fixture(),draft=parseWorkflowRegistrationFile(JSON.stringify({...f,manifest:{executionAdmission:true},weightAuthorizations:[{allowed:true}]}),"C:/cpu-project/entry.json");expect(draft).toEqual({source:f.source,selection:f.selection,selectionEnvelope:undefined,voiceOptionBindings:undefined});expect("manifest" in draft).toBe(false);});
it("새 API workflow를 검사하고 원본·snapshot·저장 버전을 구분합니다",async()=>{const f=fixture(),before=state.graphs.get(f.source.workflowPath),entry=await register(f);expect(entry.issues).toEqual([]);expect(entry.manifest).toBeDefined();expect(entry.source.workflowPath).not.toBe(f.source.workflowPath);expect(entry.originalWorkflowPath).toBe(f.source.workflowPath);expect(state.graphs.get(f.source.workflowPath)).toBe(before);expect(state.graphs.get(entry.source.workflowPath)).toBe(before);expect(listWorkflowLibrary()[0].manifest?.promptTarget).toEqual(entry.manifest!.promptTarget);});
it("V2 파일 가져오기→새 검사→미러 저장→재시작 로드에서 literal envelope와 hash를 보존합니다",async()=>{const f=fixture(),envelope=await migrateWorkflowSelectionV1ToV2(f.selection,{originalV1SelectionJson:JSON.stringify(f.selection,null,3)}),draft=parseWorkflowRegistrationFile(JSON.stringify({source:f.source,selection:f.selection,selectionEnvelope:envelope}),"C:/cpu-project/v2-entry.json");const entry=await inspectAndRegisterWorkflow({...draft,projectId:"cpu-project"});expect(entry.manifest?.schemaVersion).toBe(2);expect(entry.selectionEnvelope).toEqual(envelope);const persisted=structuredClone(state.mirror.mock.calls.at(-1)![1]);window.localStorage.setItem(KEY,"[]");state.sections.get("comfy-workflow-library")!.write(persisted);const loaded=listWorkflowLibrary()[0];expect(loaded.selectionEnvelope).toEqual(envelope);expect((loaded.manifest as any).selectionEnvelope.originalV1SelectionJson).toBe(envelope.originalV1SelectionJson);expect(workflowEntryForTarget(loaded.manifest!.promptTarget).revisionId).toBe(entry.revisionId);});
it("H3 V2 초안의 미검토 노드·weight 오류도 envelope를 잃지 않고 보존합니다",async()=>{const {draft}=offlineWorkflowV2Draft("h3-ref2va-2-identity","C:/cpu-project/h3.api.json");const raw=readFileSync(resolve("src-tauri/resources/comfy-v2-graphs/h3-ref2va-2-identity.api.json"),"utf8");state.graphs.set(draft.source.workflowPath,raw);const imported=parseWorkflowRegistrationFile(JSON.stringify(draft),"C:/cpu-project/h3-entry.json");const entry=await inspectAndRegisterWorkflow({...imported,projectId:"cpu-project"});expect(entry.manifest).toBeUndefined();expect(entry.issues.length).toBeGreaterThan(0);expect(listWorkflowLibrary()[0].selectionEnvelope).toEqual(draft.selectionEnvelope);expect(listWorkflowLibrary()[0].selectionEnvelope?.originalV1SelectionSha256).toBe(draft.selectionEnvelope.originalV1SelectionSha256);});
it("같은 이름·workflow ID의 다시 등록은 이전 버전을 삭제하거나 선택을 바꾸지 않습니다",async()=>{const f=fixture(),one=await register(f);f.graph["4"].inputs.text="CPU changed original";state.graphs.set(f.source.workflowPath,JSON.stringify(f.graph));const two=await register(f);expect(listWorkflowLibrary()).toHaveLength(2);expect(two.source.workflowId).not.toBe(one.source.workflowId);expect(one.source.title).toBe(two.source.title);expect(two.originWorkflowId).toBe(one.source.workflowId);expect(workflowEntryForTarget(one.manifest!.promptTarget).source.workflowPath).toBe(one.source.workflowPath);expect(state.graphs.get(one.source.workflowPath)).not.toBe(state.graphs.get(two.source.workflowPath));});
it("모델이 사라진 새 검사는 구체 오류의 초안으로 보존하고 이전 통과 버전을 유지합니다",async()=>{const f=fixture(),old=await register(f);state.catalog.UNETLoader.input.required.unet_name=[["different-model.safetensors"]];const next=await register(f);expect(next.manifest).toBeUndefined();expect(next.issues.some(issue=>issue.code==="invalid_input_value")).toBe(true);expect(listWorkflowLibrary()).toHaveLength(2);expect(workflowEntryForTarget(old.manifest!.promptTarget).revisionId).toBe(old.revisionId);});
it("미설치 노드는 이름과 입력을 포함한 오류를 저장하고 실행 manifest를 만들지 않습니다",async()=>{const f=fixture();f.graph["4"].class_type="UninstalledCPUText";state.graphs.set(f.source.workflowPath,JSON.stringify(f.graph));const entry=await register(f);expect(entry.manifest).toBeUndefined();expect(entry.issues).toContainEqual(expect.objectContaining({code:"missing_node",nodeId:"4",message:expect.stringContaining("UninstalledCPUText")}));});
it("ComfyUI 편집용 JSON은 API export 안내 후 저장·변환·생성을 하지 않습니다",async()=>{const f=fixture();state.graphs.set(f.source.workflowPath,JSON.stringify({nodes:[],links:[]}));await expect(register(f)).rejects.toThrow("workflow_api_export_required");expect(listWorkflowLibrary()).toEqual([]);expect(state.native.mock.calls.some(([command])=>command==="comfy_workflow_store_revision")).toBe(false);});
it("취소한 파일 선택은 기존 저장 버전과 편집 입력을 변경하지 않습니다",async()=>{const f=fixture();await register(f);const saved=window.localStorage.getItem(KEY);expect(await chooseWorkflowRegistrationFile("C:/cpu-project")).toBeNull();expect(window.localStorage.getItem(KEY)).toBe(saved);});
it("읽기 이후 파일 변경이나 디스크 저장 실패는 이전 등록을 덮어쓰지 않습니다",async()=>{const f=fixture();await register(f);const saved=window.localStorage.getItem(KEY);state.snapshotError=true;await expect(register(f)).rejects.toThrow("source changed");expect(window.localStorage.getItem(KEY)).toBe(saved);state.snapshotError=false;state.mirror.mockRejectedValueOnce(new Error("CPU settings disk full"));await expect(register(f)).rejects.toThrow("disk full");expect(window.localStorage.getItem(KEY)).toBe(saved);});
it("동시에 두 파일을 가져와도 등록을 직렬 저장하여 양쪽 버전을 유지합니다",async()=>{await Promise.all([register(fixture("one")),register(fixture("two"))]);expect(listWorkflowLibrary().map(e=>e.source.workflowId)).toEqual(["one","two"]);expect(state.mirror.mock.calls.at(-1)![1]).toHaveLength(2);});
it("등록된 프로젝트를 다른 프로젝트로 바꾸지 않고 별도 workflow ID를 요구합니다",async()=>{const f=fixture();await register(f);await expect(inspectAndRegisterWorkflow({...f,projectId:"another"})).rejects.toThrow("another_project");expect(listWorkflowLibrary()).toHaveLength(1);});
it("낡은 hash·다른 역할·모델은 문장용 target과 실행 target에서 모두 차단합니다",async()=>{const e=await register(fixture()),target=e.manifest!.promptTarget;for(const patch of [{workflowSha256:"f".repeat(64)},{roleId:"foreign"},{modelRuleId:"foreign"}]){expect(()=>workflowEntryForTarget({...target,...patch})).toThrow("target_stale");expect(()=>workflowPromptContext({...target,...patch})).toThrow("target_stale");}});
it("이전 V2 저장본에 top-level envelope가 없어도 manifest의 정확한 원문을 복구합니다",async()=>{const f=fixture(),envelope=await migrateWorkflowSelectionV1ToV2(f.selection),e=await register(f,envelope);window.localStorage.setItem(KEY,JSON.stringify([{...e,selectionEnvelope:undefined}]));expect(listWorkflowLibrary()[0].selectionEnvelope).toEqual(envelope);});
it("깨진 V2 envelope는 V1이나 실행 통과 상태로 자동 전환하지 않습니다",async()=>{const f=fixture(),e=await register(f,await migrateWorkflowSelectionV1ToV2(f.selection));window.localStorage.setItem(KEY,JSON.stringify([{...e,selectionEnvelope:{schemaVersion:1}}]));const loaded=listWorkflowLibrary()[0];expect(loaded.manifest).toBeUndefined();expect(loaded.issues).toContainEqual(expect.objectContaining({code:"workflow_stored_v2_envelope_invalid"}));expect((loaded.selectionEnvelope as any).schemaVersion).toBe(1);});
it("명시 INDEX 선택은 상대 entry만 읽고 V2 envelope와 원래 graph hash를 전달합니다",async()=>{const f=fixture(),envelope=await migrateWorkflowSelectionV1ToV2(f.selection),index={entries:[{id:"cpu",model:"CPU",operation:"text-to-image",referenceCount:0,graphSha256:await workflowSha256(state.graphs.get(f.source.workflowPath)!),relativeAppRegistrationEntries:{v1:null,v2:"Candidates/cpu/v2/app-registration-entry.json"}}]};const parsed=parseWorkflowImportFile(JSON.stringify(index),"C:/cpu-project/INDEX.json");expect(parsed.kind).toBe("index");if(parsed.kind!=="index")throw new Error("index expected");state.graphs.set("C:/cpu-project/Candidates/cpu/v2/app-registration-entry.json",JSON.stringify({source:f.source,selection:f.selection,selectionEnvelope:envelope}));const imported=await readWorkflowIndexRegistration(parsed.root,parsed.entries[0],"v2");expect(imported.draft.selectionEnvelope).toEqual(envelope);expect(imported.expectedGraphSha256).toBe(index.entries[0].graphSha256);expect(state.native.mock.calls.at(-1)).toEqual(["comfy_workflow_read_library_entry",{root:"C:/cpu-project",relativePath:"Candidates/cpu/v2/app-registration-entry.json"}]);});
it("INDEX의 경로 탈출·절대경로·잘못된 V2 표시는 읽기 전에 거절합니다",()=>{for(const relative of ["../outside.json","C:/outside.json","https://cpu.invalid/entry.json","folder\\entry.json"]){expect(()=>parseWorkflowImportFile(JSON.stringify({entries:[{id:"cpu",graphSha256:"a".repeat(64),relativeAppRegistrationEntries:{v2:relative}}]}),"C:/cpu-project/INDEX.json")).toThrow("unsafe_entry_path");}expect(state.native).not.toHaveBeenCalled();});
it("실제 선택 UI 렌더링은 저장된 V1·V2·각 버전 hash를 구분하고 타 프로젝트를 제외합니다",async()=>{const f=fixture(),one=await register(f),two=await register(f,await migrateWorkflowSelectionV1ToV2(f.selection));const foreign=structuredClone(one);foreign.source.workflowId="foreign";foreign.source.title="외부 프로젝트 항목";foreign.projectScope="another";window.localStorage.setItem(KEY,JSON.stringify([...listWorkflowLibrary(),foreign]));const html=renderToStaticMarkup(createElement(WorkflowPromptSelect,{kind:"image",projectId:"cpu-project",value:two.manifest!.promptTarget,onChange:()=>{throw new Error("render must not change selection");}}));expect(html).toContain("V1");expect(html).toContain("V2");expect(html).toContain(two.workflowSha256!.slice(0,8));expect(html).toContain("selected=");expect(html).not.toContain("외부 프로젝트 항목");});
it("실제 역할 편집 UI는 가져온 loader·본문·참조·scalar 매핑을 렌더링합니다",()=>{const f=fixture("with-reference",true),html=renderToStaticMarkup(createElement(WorkflowRoleEditor,{draft:{source:f.source,selection:f.selection},graph:f.graph,onChange:()=>{throw new Error("render must not mutate");}}));expect(html).toContain("실제 모델 로더");expect(html).toContain("UNETLoader");expect(html).toContain("reference");expect(html).toContain("seed");expect(html).toContain("본문 슬롯");expect(html).toContain("수집할 출력 노드");});
it("동일 ID의 다른 원본 파일은 각 버전의 원래 경로를 정확히 보존합니다",async()=>{const f=fixture(),old=await register(f);const source={...f.source,workflowPath:"C:/cpu-project/other-original.api.json"};state.graphs.set(source.workflowPath,JSON.stringify(f.graph));const next=await inspectAndRegisterWorkflow({source,selection:f.selection,projectId:"cpu-project"});expect(next.originalWorkflowPath).toBe(source.workflowPath);expect(old.originalWorkflowPath).toBe(f.source.workflowPath);expect(listWorkflowLibrary()).toHaveLength(2);});
it("R2 등록한 주 역할 외의 role은 별도 revision 전에는 선택·작성·실행 버튼에 허용하지 않습니다",async()=>{const f=fixture();const branch=structuredClone(f.graph);for(const [id,node] of Object.entries(branch)){const copy=structuredClone(node);for(const [key,value] of Object.entries(copy.inputs))if(Array.isArray(value))copy.inputs[key]=[String(Number(value[0])+10),value[1]];f.graph[String(Number(id)+10)]=copy;}f.selection.slots.push({id:"secondary-positive",semantic:"positive",nodeId:"14",input:"text",required:true},{id:"secondary-negative",semantic:"negative",nodeId:"15",input:"text",required:true});f.selection.promptRoles.push({...f.selection.promptRoles[0],id:"secondary",loaderNodeIds:["11"],positiveSlotIds:["secondary-positive"],negativeSlotIds:["secondary-negative"]});f.selection.outputNodeIds.push("19");state.graphs.set(f.source.workflowPath,JSON.stringify(f.graph));const e=await register(f);expect(e.issues).toEqual([]);const target={...e.manifest!.promptTarget,roleId:"secondary"};expect(e.manifest).toBeDefined();const html=renderToStaticMarkup(createElement(WorkflowPromptSelect,{kind:"image",projectId:"cpu-project",value:e.manifest!.promptTarget,onChange:()=>{}}));expect(html).not.toContain("flux2/secondary");expect(()=>workflowPromptContext(target)).toThrow("workflow_role_revision_required");const button=renderToStaticMarkup(createElement(ComfyGenerateButton,{kind:"image",prompt:{en:"수동 문장",ko:""},projectName:"CPU",projectId:"cpu-project",assetType:"character-generated",ownerName:"CPU",stem:"CPU",target:{kind:"character",id:"actor"},workflowTarget:target,onDone:()=>{}}));expect(button).toMatch(/<button[^>]*disabled=""[^>]*title=/);});
it("R3 실제 프로젝트 기본 selector 호출에도 저장 project scope를 전달합니다",async()=>{const e=await register(fixture()),foreign=structuredClone(e);foreign.source.workflowId="foreign";foreign.source.title="외부 프로젝트 항목";foreign.projectScope="another";window.localStorage.setItem(KEY,JSON.stringify([e,foreign]));const props:any={draft:{...newProjectDraft(),batchEngines:{image:"comfy",video:"magnific"}},projectId:"cpu-project",onChange:()=>{}};const html=renderToStaticMarkup(createElement(BatchToolsField,props));expect(html).not.toContain("외부 프로젝트 항목");const unsaved=renderToStaticMarkup(createElement(WorkflowPromptSelect,{kind:"image",onChange:()=>{}}));expect(unsaved).not.toContain("동일 표시 이름");});
it("R5 maskVideo는 CPU mask 규약 경로가 구현되지 않아 등록 단계에서 명시 unsupported 초안입니다",async()=>{const f=fixture("mask-video",true);f.selection.slots.find(s=>s.id==="reference")!.semantic="maskVideo";f.selection.slots.find(s=>s.id==="reference")!.maskConvention="white-edit";f.selection.referenceGroups[0]={...f.selection.referenceGroups[0],role:"maskVideo",mediaKind:"video"};const e=await register(f);expect(e.manifest).toBeUndefined();expect(e.issues).toContainEqual(expect.objectContaining({code:"workflow_mask_video_unsupported"}));});
it("F1 일반 명시 사용자 진술→unknown 라이선스 manifest 검사 경로를 보존하고 forged scope는 저장하지 않습니다",async()=>{
 const f=fixture("generic-authorization"),files=["cpu-model.safetensors","cpu-clip.safetensors","cpu-vae.safetensors"].map((name,index)=>({category:["diffusion_models","text_encoders","vae"][index],name,sha256:"a".repeat(64)})),original=state.native.getMockImplementation()!;
 state.native.mockImplementation(async(command,args)=>{if(command==="comfy_workflow_authorization_options")return {registrySha256:"b".repeat(64),presets:[{id:"cpu-flux2",modelRuleId:"flux2",files}]};const result=await original(command,args);if(command==="comfy_workflow_preflight")result.verifiedWeights=result.verifiedWeights.map((weight:any)=>({...weight,license:"unknown"}));return result;});
 expect((await register(f)).manifest).toBeUndefined();const {recordWorkflowUserAuthorization}=await import("./comfyWorkflowLibrary"),raw={projectId:"cpu-project",presetId:"cpu-flux2",modelRuleId:"flux2",registrySha256:"b".repeat(64),files,statement:{kind:"user-reported",evidence:"CPU statement fixture; not real authorization",sourceThreadId:"cpu-fixture",reportedAtUtc:"2026-10-07T00:00:00Z"}};
 const grants=await recordWorkflowUserAuthorization(raw);expect(grants).toHaveLength(3);expect((await register(f)).manifest?.weightRequirements.every(weight=>weight.authorization?.modelRuleId==="flux2")).toBe(true);const before=state.mirror.mock.calls.length;await recordWorkflowUserAuthorization(raw);expect(state.mirror.mock.calls).toHaveLength(before);
 for(const altered of [{...raw,projectId:"foreign"},{...raw,registrySha256:"c".repeat(64)},{...raw,files:[{...files[0],name:"unreviewed.safetensors"}]},{...raw,statement:{...raw.statement,evidence:""}},{...raw,allowed:true}])await expect(recordWorkflowUserAuthorization(altered)).rejects.toThrow();expect(state.mirror.mock.calls).toHaveLength(before);
 const persisted=structuredClone(state.sections.get("workflow-project-authorizations")!.read());state.sections.get("workflow-project-authorizations")!.write([]);expect((await register(f)).manifest).toBeUndefined();state.sections.get("workflow-project-authorizations")!.write(persisted);expect((await register(f)).manifest).toBeDefined();
 state.mirror.mockRejectedValueOnce(new Error("CPU authorization disk full"));await expect(recordWorkflowUserAuthorization({...raw,statement:{...raw.statement,evidence:"different CPU statement"}})).rejects.toThrow("disk full");expect(state.sections.get("workflow-project-authorizations")!.read()).toEqual(persisted);
});

it("F4 역할별 다른 모델은 임의 선택 없이 draft와 명시 unsupported 사유로 남습니다",async()=>{
 const f=fixture("mixed-model-role");f.graph["14"]=structuredClone(f.graph["4"]);f.selection.slots.push({id:"secondaryPositive",semantic:"positive",nodeId:"14",input:"text",required:true});f.selection.promptRoles.push({id:"secondary",modelRuleId:"qwen-image",loaderNodeIds:["1"],positiveSlotIds:["secondaryPositive"],negativeSlotIds:[],negativeSupport:"unsupported"});state.graphs.set(f.source.workflowPath,JSON.stringify(f.graph));
 const entry=await register(f);expect(entry.manifest).toBeUndefined();expect(entry.selection.promptRoles[1].modelRuleId).toBe("qwen-image");expect(entry.issues.map(i=>i.code)).toContain("workflow_mixed_model_roles_unsupported");
});

it("F1 동시에 요청한 사용자 진술은 서로의 모델 범위를 잃지 않고 원문을 보존합니다",async()=>{
 const {recordWorkflowUserAuthorization,environmentFromPreflight}=await import("./comfyWorkflowLibrary");
 const original=state.native.getMockImplementation()!,file={category:"diffusion_models",name:"cpu-model.safetensors",sha256:"a".repeat(64)},options={registrySha256:"b".repeat(64),presets:[{id:"one",modelRuleId:"flux2",files:[file]},{id:"two",modelRuleId:"qwen-image",files:[file]}]};
 state.native.mockImplementation(async(command,args)=>command==="comfy_workflow_authorization_options"?options:original(command,args));
 let release!:()=>void;state.mirror.mockImplementationOnce(()=>new Promise<void>(resolve=>{release=resolve;}));
 const statement={kind:"user-reported" as const,evidence:"  Synthetic CPU original statement; never real authorization.  ",sourceThreadId:"cpu-fixture",reportedAtUtc:"2026-10-07T00:00:00Z"};
 const input=(index:number)=>({projectId:"cpu-project",presetId:options.presets[index].id,modelRuleId:options.presets[index].modelRuleId,registrySha256:options.registrySha256,files:[file],statement});
 const one=recordWorkflowUserAuthorization(input(0)),two=recordWorkflowUserAuthorization(input(1));
 for(let i=0;i<20&&!release;i++)await new Promise(resolve=>setTimeout(resolve,0));
 expect(state.mirror).toHaveBeenCalledTimes(1);release();await Promise.all([one,two]);
 const stored=JSON.parse(localStorage.getItem("ai-video-storage.workflow-project-authorizations.v1")!);expect(stored).toHaveLength(2);expect(stored.map((g:any)=>g.modelRuleId)).toEqual(["flux2","qwen-image"]);expect(stored.every((g:any)=>g.evidence===statement.evidence)).toBe(true);
 const preflight:any={systemStats:{system:{}},catalog:{},sourceEvidence:"reported-commit-matches-disk",verifiedWeights:[]};expect(environmentFromPreflight(preflight,"cpu-project","qwen-image").weightAuthorizations).toEqual([stored[1]]);
});
