import type { Tutorial } from "./types";

/*
  페이지별 튜토리얼 — «작업하다 막혔을 때» 그 화면의 기능을 하나씩.

  
  한 바퀴(full.ts)가 «순서» 라면 여기는 «사전» 입니다. 걸음마다 단추 하나·칸 하나이고,
  이름은 화면 코드의 것을 그대로 씁니다. 구도잡기는 기능이 많아 planner.ts 에 따로 있습니다.
*/

const P = "/project/:id" as const;

const PROJECTS: Tutorial = {
  id: "page-projects",
  kind: "page",
  page: "projects",
  title: "프로젝트 보드",
  summary: "작품 목록을 읽는 법을 훑고, 마지막에 첫 작품을 하나 만듭니다.",
  steps: [
    {
      id: "page-projects-stats",
      route: "/",
      page: "projects",
      anchor: "projects-stats",
      title: "요약 숫자",
      body:
        "활성 프로젝트 · 총 씬 · 생성된 자산 · AI 최적화 횟수 네 칸은 전부 실제 저장된 프로젝트에서 셉니다. 가짜 예시 카드는 없습니다 — 아직 아무것도 안 만들었으면 네 칸이 0 입니다.",
    },
    {
      id: "page-projects-search",
      route: "/",
      page: "projects",
      anchor: "projects-search",
      title: "검색과 보기 방식",
      body: "작품이 쌓이면 검색 칸이 제목으로 걸러 줍니다. 오른쪽 두 단추로 바둑판과 목록 보기를 바꿉니다.",
    },
    {
      id: "page-projects-reload",
      route: "/",
      page: "projects",
      anchor: "projects-reload",
      title: "폴더 다시 읽기",
      body:
        "이 목록은 저장 폴더의 거울입니다. 탐색기에서 프로젝트 폴더를 지우거나 옮겼다면 이 새로 고침 단추를 누르세요.",
      why: "폴더가 원본이라 앱에서 지우는 것이 아니라 폴더를 지우는 것이 진짜 삭제입니다.",
    },
    {
      id: "page-projects-card",
      route: "/",
      page: "projects",
      anchor: "projects-grid",
      title: "카드는 이렇게 읽습니다",
      body:
        "작품을 하나 만들면 여기 카드가 섭니다. 카드에는 상태 뱃지(초안 · 진행 중), 씬 수, 자산 수, 마지막으로 고친 날짜가 있고, 누르면 채운 단계 중 마지막 다음으로 바로 갑니다 — 다 채웠으면 확인 단계입니다.",
    },
    {
      id: "page-projects-hide",
      route: "/",
      page: "projects",
      anchor: "projects-card-hide",
      title: "숨기기 — 지우기가 아닙니다",
      body:
        "카드에 마우스를 올리면 눈 단추가 나옵니다. 목록에서만 감출 뿐 프로젝트 폴더와 그 안의 그림·영상은 그대로 남습니다. 진짜로 지우려면 탐색기에서 폴더를 지우세요.",
      why: "폴더 안에 몇 시간씩 뽑은 그림이 들어 있습니다. 클릭 한 번에 그게 다 사라지면 되돌릴 길이 없습니다.",
    },
    {
      id: "page-projects-hidden",
      route: "/",
      page: "projects",
      anchor: "projects-hidden",
      title: "숨긴 프로젝트",
      body: "감춘 것이 있으면 목록 아래에 «숨긴 프로젝트 (N)» 이 생깁니다. 펼치면 폴더 이름과 함께 늘어서고 «다시 보이기» 로 되돌립니다.",
    },
    {
      id: "page-projects-new",
      route: "/",
      page: "projects",
      anchor: "projects-new",
      title: "이제 하나 만들어 봅니다",
      body:
        "오른쪽 위 «새 프로젝트» 를 누릅니다. 아직 하나도 없으면 가운데의 «첫 프로젝트 만들기» 도 같은 자리입니다. 누르면 네 단계 화면이 열립니다 — 주제 설정 · 캐릭터 · 씬 구성 · 확인.",
      action: "해 볼 것: «새 프로젝트» 를 누르세요.",
    },
    {
      id: "page-projects-made",
      route: "/new-project",
      page: "basics",
      anchor: "basics-title",
      title: "제목을 적으면 폴더가 생깁니다",
      body:
        "여기까지 왔으면 보드는 다 본 것입니다. «제목» 을 적는 순간 저장 폴더 안에 그 이름으로 폴더가 생기고, 그때부터 손대는 것마다 저절로 저장됩니다. 저장 단추는 없습니다.",
      action: "해 볼 것: 제목을 하나 적으세요. 프로젝트로 돌아오면 보드에 카드가 하나 서 있습니다.",
      why:
        "나머지 세 단계(캐릭터 · 씬 구성 · 확인)는 각 단계의 튜토리얼에 따로 있습니다. 위 띠의 «튜토리얼» 은 늘 «지금 있는 화면» 의 것만 보여 줍니다.",
    },
  ],
};

const BASICS: Tutorial = {
  id: "page-basics",
  kind: "page",
  page: "basics",
  title: "주제 설정",
  summary: "작품 정보와 장르·스타일·시대를 정합니다. 이후 모든 프롬프트의 머리말이 됩니다.",
  steps: [
    {
      id: "page-basics-bootstrap",
      route: "/new-project",
      page: "basics",
      anchor: "basics-bootstrap",
      title: "AI 로 일괄 생성",
      body:
        "시나리오를 붙여넣어 작품 정보 · 캐릭터 · 배경 · 장면 · 컷 구도 · 키컷 프롬프트까지 한 번에 만드는 창입니다. API 키가 있어야 켜집니다. 이미 뭔가 적어 두었으면 한 줄 단추로 접혀 있습니다.",
    },
    {
      id: "page-basics-bootstrap-mode",
      route: "/new-project",
      page: "basics",
      anchor: "bootstrap-mode",
      title: "덧붙이기 · 비우고 새로",
      body:
        "«이미 있는 것에 덧붙이기» 는 제목·줄거리를 두고 카드만 뒤에 붙입니다. «비우고 새로» 는 캐릭터·배경·장면 목록을 비우고 넣는데, 그림이 붙은 카드는 남깁니다 — 카드를 없애면 그 인물 폴더를 앱에서 지울 길이 사라집니다. 장면은 제목이 같아도 걸러지지 않고 뒤에 붙습니다.",
    },
    {
      id: "page-basics-bootstrap-again",
      route: "/new-project",
      page: "basics",
      anchor: "bootstrap-run",
      title: "상세만 다시 만들기 · 중지",
      body:
        "받아 둔 작품 정보가 있으면 «상세만 다시 만들기» 가 늘 보입니다. 제목·줄거리·인물 목록은 그대로 두고 2·3단계(상세·장면·구도)만 다시 부릅니다. 도는 중에는 «중지» 로 끊고, 지난 답은 «지난 일괄 생성» 선반에서 되돌립니다.",
    },
    {
      // 4단계는 «만들기» 옆 체크라 같은 앵커입니다. 그래서 생긴 단계.
      id: "page-basics-bootstrap-rich",
      route: "/new-project",
      page: "basics",
      anchor: "bootstrap-run",
      title: "카드마다 프롬프트 자세히 쓰기 (4/4)",
      body:
        "«만들기» 옆의 체크로, 기본은 켜짐입니다. 3단계는 한 답에 컷 전부를 몰아 받아 컷마다 한 문단이 고작이라, 답을 넣은 뒤 인물·장소 시트와 컷의 그림·영상 프롬프트를 카드마다 «프롬프트 작성» 과 같은 요청으로 따로 받습니다. 진행 줄에 «4/4 카드마다 프롬프트를 자세히 쓰는 중 — n/N번째» 가 뜹니다. 요금과 시간이 카드 수만큼 드니 끄면 3단계의 짧은 프롬프트와 규칙 조립만 남습니다. «넣고 이미지·영상까지 바로 뽑기» 는 이 단계가 끝난 뒤에야 줄을 세웁니다.",
    },
    {
      id: "page-basics-info",
      route: "/new-project",
      page: "basics",
      anchor: "basics-info",
      title: "작품 정보",
      body:
        "다섯 칸 — 제목 · 한 줄 줄거리 · 줄거리 · 톤·분위기 · 분량입니다. 제목은 폴더 이름이 되고 나중에 바꿔도 폴더는 그대로입니다. 분량(예: 3분 단편)은 일괄 생성이 컷 길이를 정할 때 봅니다.",
    },
    {
      id: "page-basics-genre",
      route: "/new-project",
      page: "basics",
      anchor: "basics-genre",
      title: "장르",
      body: "무엇이 나오는가 — 소재입니다. 여러 개 켤 수 있고 켠 수가 제목 옆에 뜹니다.",
    },
    {
      id: "page-basics-style",
      route: "/new-project",
      page: "basics",
      anchor: "basics-style",
      title: "비주얼 스타일",
      body: "어떻게 그려지는가 — 화풍입니다. 장르와 따로 두는 까닭은 «판타지» 를 실사로도 애니로도 그릴 수 있어서입니다.",
    },
    {
      id: "page-basics-era",
      route: "/new-project",
      page: "basics",
      anchor: "basics-era",
      title: "시대 배경",
      body:
        "단추로 고르거나 «연도로 직접 잡기» 의 «구간 추가» 로 «1900년대 ~ 2000년대» 처럼 적습니다. 연도를 적으면 단추는 흐려집니다 — 두 곳에서 정하면 반드시 어긋나서 더 좁게 짚은 쪽이 이깁니다. «시대를 특정하지 않음» 을 켜면 «어느 시대에도 묶이지 않음» 이라고 프롬프트에 분명히 적습니다.",
    },
    {
      id: "page-basics-preview",
      route: "/new-project",
      page: "basics",
      anchor: "basics-preview",
      title: "프롬프트에 이렇게 들어갑니다",
      body: "고른 것이 영어로 어떻게 나가는지 미리 보는 칸입니다. «판타지» 를 골랐을 때 영어로 뭐라고 나가는지 모르면 결과를 못 고칩니다.",
    },
    {
      id: "page-basics-cover",
      route: "/new-project",
      page: "basics",
      anchor: "basics-cover",
      advanceOn: "manual",
      title: "대표 그림 — 보드 카드에 뜨는 한 장",
      body: "프로젝트 보드에서 작품을 알아보는 그림입니다. 아무것도 안 해도 작품 안에서 한 장을 저절로 골라 걸어 두지만(장소 → 인물 → 컷 차례), «대표 그림 로컬로 만들기» 를 누르면 제목·로그라인·장르·화풍을 엮은 프롬프트로 이 컴퓨터의 모델이 한 장 뽑아 붙입니다. 이미 뽑아 둔 것 중에서 고르려면 «작품 안의 그림에서 고르기» 입니다.",
      action: "해 볼 것: 대표 그림 칸을 확인하고, 바꾸고 싶으면 «작품 안의 그림에서 고르기» 를 눌러 보세요.",
      why: "로컬 모델로 뽑으므로 API 요금이 나가지 않습니다. 정해 둔 것을 풀면 다시 작품 안에서 저절로 고릅니다 — 파일은 지우지 않습니다.",
    },
    {
      id: "page-basics-nav",
      route: "/new-project",
      page: "basics",
      anchor: "project-progress",
      title: "프로그래스 바와 다음",
      body:
        "위 네 동그라미는 «채웠는가», 사이 선은 «가 봤는가» 입니다. 지금 있는 곳은 테두리로, 건너뛴 곳은 점선으로 표시됩니다. 아무 단계나 눌러 오갈 수 있고, 아래 «다음» «건너뛰기» «이전» 으로도 움직입니다. 저장 단추는 없습니다 — 손을 멈추면 1.5초 뒤, 창을 가릴 때, 화면을 떠날 때 저절로 저장합니다.",
    },
  ],
};

const CHARACTERS: Tutorial = {
  id: "page-characters",
  kind: "page",
  page: "characters",
  title: "캐릭터",
  summary: "인물 카드 하나의 칸을 위에서 아래로 — 레퍼런스, 분석, 프롬프트, 뽑은 그림, 시트, 변형.",
  steps: [
    {
      id: "page-characters-panel",
      route: P,
      page: "characters",
      anchor: "character-panel",
      title: "인물 패널",
      body:
        "인물마다 패널 하나입니다. 이름 줄 · 원본 카드(왼쪽) → 변형 카드(오른쪽) 계보 · 다른 원본 · 보유 애셋 · 제작한 캐릭터 시트 · «캐릭터 시트 제작» 순서입니다. 이름 옆 화살표로 패널을 한 줄로 접습니다. 배경·에셋도 같은 상자를 씁니다.",
    },
    {
      id: "page-characters-add",
      route: P,
      page: "characters",
      anchor: "characters-add",
      title: "캐릭터 추가 · 다른 작품에서 끌어오기",
      body:
        "목록 끝의 «캐릭터 추가» 는 빈 카드를 만들고 바로 엽니다. «다른 작품에서 캐릭터 끌어오기» 는 다른 프로젝트의 카드와 그림을 이 작품 폴더로 복사해 들여옵니다 — 시리즈물처럼 인물을 나눠 쓸 때.",
      why: "복사인 까닭은, 한 카드를 두 작품이 가리키면 «화면에서 지우면 원본도 지운다» 는 규칙이 무너지기 때문입니다.",
    },
    {
      id: "page-characters-references",
      route: P,
      page: "characters",
      anchor: "card-references",
      title: "레퍼런스 이미지와 활용",
      body:
        "왼쪽 스트립에 «레퍼런스 이미지 추가» 로 넣거나 끌어다 놓습니다. 썸네일에 마우스를 올리면 복사 · 폴더 열기 · 가위가 뜹니다. 스트립 아래 세 단추(«이 인물 그대로» · «요소만 참고» · «참고 안 함»)가 레퍼런스를 어떻게 볼지입니다 — 배경은 «이 장소 그대로», 에셋은 «이 물건 그대로». 모델은 이걸 스스로 판단하지 못합니다. 태그를 걸려면 폴더에서 끌어다 «추가 외형 묘사» 칸에 놓으세요.",
    },
    {
      id: "page-characters-basics",
      route: P,
      page: "characters",
      anchor: "card-basics",
      title: "기본 정보",
      body:
        "이름 · 역할 · 형태(사람형 · 동물형 · 그 밖의 존재) · 성별(여성형 · 남성형 · 중립형) · 키(cm) · 체격. 키와 체형은 그림에서 못 읽으므로 여기 값이 프롬프트에 그대로 갑니다. 이름은 파일 이름의 앞부분이라 바꾸면 폴더와 파일 이름이 따라가고, 바꾸기 전에 한 번 묻습니다.",
    },
    {
      id: "page-characters-analysis",
      route: P,
      page: "characters",
      anchor: "card-analysis",
      title: "이미지 분석",
      body:
        "«이미지 분석» 은 API 로 바로, «LLM 요청문» 은 요청 글을 복사해 밖에서 답을 받아 «② 결과 넣기» 에 붙여넣는 길입니다. 도는 동안 마우스를 올리면 «중지» 가 됩니다. 결과 칸은 직접 고칠 수 있고, 다시 분석하면 앞의 판이 «받아 둔 분석» 에 남습니다. 같은 부모의 다른 카드 분석은 «분석 가져오기» 로 옮깁니다.",
    },
    {
      id: "page-characters-profile",
      route: P,
      page: "characters",
      anchor: "card-profile",
      title: "특징 정하기",
      body: "성격 · 말투 · 버릇처럼 그림에 안 찍히는 것을 정합니다. 시트의 프로필 글상자에 글자로 찍혀 영상 모델이 연기할 때 읽습니다. 그림 프롬프트에는 안 실립니다.",
    },
    {
      id: "page-characters-blueprint",
      route: P,
      page: "characters",
      anchor: "card-blueprint",
      title: "캐릭터 레퍼런스 구성",
      body:
        "시트에 어떤 칸을 넣을지 그룹별로 켜고 끕니다 — 정체성·체형, 얼굴·헤어, 연기·동작, 외형·의상, 소품·상호작용, 색·재질·제작 메모. «전체» 로 한 번에 켭니다. 여기서 고른 칸이 «프롬프트 작성» 의 재료입니다.",
    },
    {
      id: "page-characters-prompt",
      route: P,
      page: "characters",
      anchor: "card-prompt-write",
      title: "프롬프트 작성 · 규칙 조립 · LLM 요청문",
      body:
        "«이미지 모델» 을 고르면 그 모델 문법으로 글이 지어집니다. «프롬프트 작성» 은 API 로, «규칙 조립» 은 API 없이 규칙으로, «LLM 요청문» 은 복사해 밖에서. 결과는 한글 프롬프트 · English Prompt 두 칸이고 «네 칸 모두 지우기» 로 비웁니다. 앞의 판은 «받아 둔 프롬프트» 에 쌓여 «되돌리기» 로 돌아갑니다.",
    },
    {
      id: "page-characters-first-reference",
      route: P,
      page: "characters",
      anchor: "card-first-reference",
      title: "첫 레퍼런스 프롬프트",
      body:
        "레퍼런스가 아직 한 장도 없을 때 쓰는 칸입니다. 이름·설명·기본 정보만으로 «맞춤 프롬프트 만들기» 를 누르면 첫 그림을 뽑을 글이 나옵니다. 여기서도 «구성» 으로 프롬프트만 든 생성기를 놓을 수 있습니다.",
    },
    {
      id: "page-characters-compose",
      route: P,
      page: "characters",
      anchor: "card-compose",
      title: "구성 · 마그니픽 · 복사 · 로컬로 뽑기",
      body:
        "칸마다 단추가 셋입니다. «구성» 은 레퍼런스와 프롬프트(@칩 연결)가 든 이미지 생성기를 마그니픽 캔버스에 놓습니다(이 앱이 켠 마그니픽 데스크톱에서만). «마그니픽» 은 글만 텍스트 노드로 붙여넣고, «복사» 는 클립보드로. 로컬 모델이 깔려 있으면 «로컬로 뽑기» 가 이 컴퓨터에서 바로 한 장 만듭니다 — 보내는 순간 @칩과 --ar 같은 매개변수를 걷어냅니다.",
    },
    {
      id: "page-characters-local",
      route: P,
      page: "characters",
      anchor: "card-local-generate",
      title: "로컬로 뽑기 — 이 컴퓨터에서",
      body:
        "«구성» 옆의 이 줄은 **마그니픽과 다른 길**입니다. 왼쪽에서 이 컴퓨터에 깔린 모델을 고르고 «로컬로 뽑기» 를 누르면 밖에 나가지 않고 여기서 한 장 만듭니다. 요금은 없고 대신 그래픽카드를 씁니다. 로컬 모델이 하나도 안 깔려 있으면 이 줄이 아예 안 보입니다.",
      why:
        "보내는 순간 @칩과 --ar 같은 매개변수를 걷어냅니다 — 로컬 모델은 그런 글자를 못 알아듣고 그대로 그림에 그려 넣습니다.",
    },
    {
      id: "page-characters-images",
      route: P,
      page: "characters",
      anchor: "card-generated-images",
      title: "생성 결과 이미지",
      body:
        "«이미지 등록» 이나 끌어다 놓기로 넣습니다. «마그니픽 후보함» 은 마그니픽 동기화 폴더를 열고, 마그니픽에 연결했으면 «가져오기» 로 이미 만들어 둔 것을 다시 뽑지 않고 끌어옵니다. 별이 대표 이미지이고, 지우면 «저장 폴더의 원본 파일도 함께 지워집니다».",
    },
    {
      id: "page-characters-crop",
      route: P,
      page: "characters",
      anchor: "card-image-crop",
      title: "가위 — 자르기 · 지우기 · 표시하기 · 동선 · 전개도 6면",
      body:
        "그림의 가위를 누르면 편집 창입니다. «자르기 · 지우기» 는 칸을 사각형으로 그려 «인물_칸 이름_자름» 으로 저장하고, 지우개 상자는 둘레 색으로 덮습니다(지우기가 자르기보다 먼저 적용). «표시하기» 는 앵커·사각형·원·자유선으로 번호를 찍고, «동선» 은 카메라·인물·빛 화살표를 그립니다. «업스케일해서 저장» 은 설정의 엔진으로 그 자리에서 키웁니다.",
    },
    {
      id: "page-characters-sheet",
      route: P,
      page: "characters",
      anchor: "character-sheet-compose",
      title: "캐릭터 시트 제작",
      body:
        "시트 합성 창에서 왼쪽 그림(원본 · 변형 · 보유 에셋 · 공용 에셋)을 캔버스에 끌어 칸을 만들고 크기를 맞춥니다. «배치도» 는 프로젝트 공용이라 이름을 적어 다른 인물에서도 고르고, 복제해 칸 몇 개만 갈아 끼웁니다. «뽑을 규격» 은 캔버스 px, «칸 이름 굽기» 는 그림 밑에 이름을 찍습니다. «시트 제작» 으로 굽고, 편집이면 «다시 굽기» 나 «새 판으로 저장». Ctrl+Z 됩니다.",
    },
    {
      id: "page-characters-variation",
      route: P,
      page: "characters",
      anchor: "character-variation",
      title: "변형 · 다른 원본 · 애셋",
      body:
        "«이 카드에서 변형» 은 부모 시트를 «정체성 기준» 으로 고정하고 바꿀 요소만 적는 창입니다(기준은 뺄 수 없고 다른 그림의 ★로 바꿀 수만 있습니다). «다른 원본» 상자의 «캐릭터 생성»(배경이면 «배경 생성»)은 어린 시절·노인처럼 같은 인물의 다른 모습, «보유 애셋» 의 «애셋 생성» 은 이 인물이 든 물건 — 셋 다 이 인물 폴더 안에 들어갑니다.",
    },
  ],
};

const SCENES: Tutorial = {
  id: "page-scenes",
  kind: "page",
  page: "scenes",
  title: "씬 구성과 컷 카드",
  summary: "장면과 컷을 만들고, 컷 카드 안의 칸 — 구도, 레퍼런스, 대사, 프롬프트, 영상, 스토리보드 — 를 하나씩.",
  steps: [
    {
      id: "page-scenes-add",
      route: P,
      page: "scenes",
      anchor: "scenes-add",
      title: "장면 추가",
      body:
        "«첫 장면 추가하기» 나 목록 끝 «장면 추가» 로 만듭니다. 장면 머리줄의 화살표로 접고 펴며, 휴지통은 «컷과 스토리보드·씬 영상이 함께 사라집니다. 저장 폴더의 원본 파일도 함께 지워집니다» 를 묻습니다.",
    },
    {
      id: "page-scenes-summary",
      route: P,
      page: "scenes",
      anchor: "scene-summary",
      title: "장면 제목과 요약",
      body:
        "«장면 제목» 과 «이 장면에서 무슨 일이 일어나는지» 요약입니다. 요약은 씬 영상 프롬프트의 첫 줄이 되므로 컷·대사·VFX 와 같은 «프롬프트 말로» 단추가 달려 있습니다.",
    },
    {
      id: "page-scenes-cut-add",
      route: P,
      page: "scenes",
      anchor: "scene-cut-add",
      title: "컷 추가와 머리줄",
      body:
        "«컷 추가» 로 컷을 세우고, 컷을 누르면 아래로 펼쳐집니다. 머리줄에는 번호 · «한 줄 제목» · 연출 칩 · 대표 그림 · «구도잡기» «구도 불러오기» «특수 배경» · 휴지통이 있습니다.",
    },
    {
      id: "page-scenes-planner-buttons",
      route: P,
      page: "scenes",
      anchor: "cut-import-composition",
      title: "구도잡기 · 구도 불러오기 · 특수 배경",
      body:
        "«구도잡기» 는 3D 창을 엽니다. «구도 불러오기» 는 이 프로젝트에서 잡아 둔 구도를 그림으로 골라 방·소품·인물 자리를 통째로 가져옵니다(카메라만 바꾸면 되는 컷에). «특수 배경» 은 도면 · 도면+동선 · 사람 크기 기준 같은 «읽는 그림» 을 뽑는 장소 카드를 엽니다.",
    },
    {
      id: "page-scenes-special-background",
      route: P,
      page: "scenes",
      anchor: "cut-special-background",
      title: "특수 배경 — 도면 · 동선 · 사람 크기 기준",
      body: "구도잡기의 방은 «서 있는 공간» 이지만, 컷을 설명하려고 뽑는 그림은 따로입니다 — 위에서 내려다본 도면, 도면에 동선 화살표를 얹은 것, 사람 크기와 견준 기준 그림 같은 «읽는 그림» 입니다. 이 단추를 누르면 그런 그림을 뽑는 **장소 카드**가 열리고, 만든 카드는 프로젝트 장소 목록에 그대로 남습니다. 카드는 구성 칸을 전부 펴서 열립니다 — 실내·실외를 가리지 않으므로 조감도·항공 수직·등각 같은 칩도 함께 보입니다.",
      action: "해 볼 것: «특수 배경» 을 눌러 카드가 어떤 칩을 내놓는지 보세요.",
      why: "구도잡기의 방 카드는 전개도·파노라마만 고르게 좁혀 두었습니다. 읽는 그림까지 거기 넣으면 방을 세우는 사람에게 쓸 일 없는 칩이 잔뜩 보입니다. 그래서 컷마다 단추를 따로 뒀습니다.",
    },
    {
      id: "page-scenes-frame",
      route: P,
      page: "scenes",
      anchor: "cut-frame",
      title: "프레임과 설명",
      body: "구도를 저장하면 왼쪽에 프레임 그림이 붙습니다. 오른쪽 «무엇이 보이고 무엇이 일어나는지» 에 컷 설명을 적습니다.",
    },
    {
      id: "page-scenes-switches",
      route: P,
      page: "scenes",
      anchor: "cut-switches",
      title: "구도 쓰기 · 레퍼런스 영상 쓰기",
      body:
        "«구도 쓰기» 는 구도 그림·배경 플레이트를 참고하는 선택입니다. «레퍼런스 영상 쓰기» 는 구도잡기 영상을 입력에 포함하는 선택이며, 켜면 카메라 설명 일부를 글에서 뺍니다. 두 스위치가 켜져 있어도 모델의 입력 지원은 별도로 확인해야 합니다. 영상 미지원 모델에서 그림만 쓸 때는 영상 스위치를 직접 끄고 프롬프트를 다시 확인하세요.",
    },
    {
      id: "page-scenes-summary-line",
      route: P,
      page: "scenes",
      anchor: "cut-summary",
      title: "구도에서 읽음",
      body: "샷 크기 · 앵글 · 거리 · 무빙은 구도를 잡으면 여기 자동으로 뜹니다. 토글로 직접 고르지 않습니다 — 두 곳에 두면 어긋나서요.",
    },
    {
      id: "page-scenes-refs",
      route: P,
      page: "scenes",
      anchor: "cut-refs",
      title: "캐릭터 · 배경 · 레퍼런스 고르기",
      body:
        "«캐릭터» 탭에서 인물 그림을 누르면 번호가 붙고 그 순서대로 올라갑니다(앞이 셉니다). 한 인물에 두 장 이상 고르면 «같은 사람의 다른 그림» 줄이 프롬프트에 붙습니다. 안 고르면 시트 한 장이 자동으로 갑니다. «배경» 탭은 장소의 6면 세트, «레퍼런스» 탭은 그 밖의 참고 그림입니다. 고른 뒤에는 «@ 다시 잇기» 를 권하는 알림이 뜹니다.",
    },
    {
      id: "page-scenes-style",
      route: P,
      page: "scenes",
      anchor: "cut-style-toggles",
      title: "연출 칩 — 스타일 · 촬영(초점거리·심도) · 조명 · 색감 · 질감 · 실사",
      body:
        "컷의 연출을 칩으로 켭니다. 작품 스타일과 샷 크기를 보고 앱이 실사 기본값을 먼저 켜 두며, 손으로 정한 것은 건드리지 않습니다. 켠 칩은 한글·영문 프롬프트 양쪽에 촬영 용어로 들어갑니다.",
    },
    {
      id: "page-scenes-dialogue",
      route: P,
      page: "scenes",
      anchor: "cut-dialogue",
      title: "대사 · 연기 지시 · VFX",
      body:
        "평소 말투로 적어도 됩니다. «연기 · 프롬프트 말로» «효과 · 프롬프트 말로» 단추가 생성기가 알아듣는 말로 바꿔 주고 바꾸기 전에 보여 줍니다. VFX 는 「비를 추가해」 처럼 시키는 말투가 아니라 「굵은 비가 비스듬히 쏟아진다」 처럼 적으세요.",
    },
    {
      id: "page-scenes-prompt",
      route: P,
      page: "scenes",
      anchor: "cut-prompt-section",
      title: "컷 프롬프트",
      body:
        "«프롬프트 작성» 은 API 로 네 칸을 채우고(구도에서 읽은 사실은 두고 문장만 다듬음), «규칙 조립» 은 API 없이, «@ 다시 잇기» 는 써 둔 문장은 두고 그림 이름(@태그)만 지금 걸린 것으로 바꿉니다. 칸마다 «구성» 으로 마그니픽에 올리고, 로컬 모델이 있으면 «로컬로 뽑기». 앞의 판은 «받아 둔 프롬프트» 에 남습니다.",
    },
    {
      id: "page-scenes-video",
      route: P,
      page: "scenes",
      anchor: "cut-video-section",
      title: "영상 프롬프트 · 영상으로 · 로컬 영상",
      body:
        "«영상 프롬프트» 아래 «Magnific 입력 지원» 은 전체 영상 레퍼런스 · 동작 전용 · 그림/첫 프레임 · 글 전용을 구분합니다. 미지원 입력은 첫 프레임으로 몰래 바꾸지 않고 전송을 멈춥니다. «영상으로» 는 데스크톱 캔버스를 구성하므로 실제 모델·영상 연결을 확인한 뒤 생성하세요. «로컬 영상» 은 별도 경로이며 선택한 로컬 엔진의 입력 제한을 따릅니다.",
    },
    {
      id: "page-scenes-storyboard",
      route: P,
      page: "scenes",
      anchor: "scene-storyboard",
      title: "스토리보드",
      body:
        "장면 아래 «스토리보드 만들기» 는 컷 대표 그림을 순서대로 6000×6000 시트로 굽습니다. 키 이미지가 없는 컷은 구도 그림이 대신 들어가고, 그림도 구도도 없는 컷은 빠집니다. 컷 그림에 «표시하기» 로 그린 동선·카메라 무빙은 칸 위에 같이 그려지고 글로도 실립니다. 시트가 생기면 «프롬프트 작성» 으로 씬 영상 프롬프트를 받고 «영상으로» 로 올립니다. 돌아온 영상은 «씬 영상» 선반에.",
    },
    {
      id: "page-scenes-inbox",
      route: P,
      page: "scenes",
      anchor: "inbox-panel",
      title: "마그니픽에서 온 것",
      body:
        "화면 위 후보함에 마그니픽 동기화로 내려온 그림·영상이 뜹니다. 타일을 눌러 여러 개 고르고 «고른 것을 …에 채택» 으로 인물·장소·컷·장면에 붙입니다. 영상은 컷이나 장면에만 붙습니다. «숨기기» 는 목록에서만 뺍니다 — 후보함 파일은 옮기거나 지우지 않습니다.",
    },
  ],
};

const FINISH: Tutorial = {
  id: "page-finish",
  kind: "page",
  page: "finish",
  title: "확인",
  summary: "작품 전체를 한눈에 보고, 스토리보드를 인쇄하고, 남은 것을 한 번에 뽑습니다.",
  steps: [
    {
      id: "page-finish-counts",
      route: P,
      page: "finish",
      anchor: "finish-counts",
      title: "인물 · 장소 · 컷 · 스토리보드 · 영상",
      body: "다섯 숫자는 이 작품에 지금 있는 것을 셉니다. 스토리보드가 장면 수보다 적으면 아직 안 구운 장면이 있다는 뜻입니다.",
    },
    {
      id: "page-finish-batch",
      route: P,
      page: "finish",
      anchor: "finish-batch",
      title: "한 번에 뽑기",
      body:
        "«지금 뽑기» 는 아직 안 뽑은 것을 인물 시트 → 컷 그림 → 스토리보드 → 씬 영상 차례로 줄에 세웁니다. 앞 걸음이 뽑은 그림이 다음 걸음의 레퍼런스가 됩니다. 무엇으로 뽑을지는 주제 설정의 «AI 로 일괄 생성» 에서 고른 값을 씁니다. «이 작품 것 모두 멈추기» 로 끊습니다.",
      why: "마그니픽 «끝까지 뽑기» 는 건당 과금입니다. 손으로 골라 가며 할 때는 «생성기를 차려 놓기» 쪽을 고르세요.",
    },
    {
      id: "page-finish-tasks",
      route: P,
      page: "finish",
      anchor: "nav-tasks",
      title: "진행은 «작업» 서랍에서",
      body:
        "위 띠의 «작업» 을 열면 돌고 있는 일과 기다리는 일이 한 줄씩 보입니다. 몇 분째인지, 소식이 끊긴 지 얼마인지가 적혀 «멈춘 건지 진행 중인지» 를 알 수 있습니다. 앱을 껐다 켜도 이어집니다. 옆의 «API 기록» 은 LLM 요청과 쓴 토큰입니다.",
    },
    {
      id: "page-finish-scene",
      route: P,
      page: "finish",
      anchor: "finish-scene-row",
      title: "장면마다 한 줄",
      body: "장면 제목 · 컷 수 · 스토리보드 시트가 늘어섭니다. 시트가 없으면 «씬 구성» 탭의 그 장면 아래에서 «스토리보드 만들기» 를 누르라는 안내가 뜹니다.",
    },
    {
      id: "page-finish-print",
      route: P,
      page: "finish",
      anchor: "finish-print",
      title: "인쇄",
      body: "«인쇄» 는 그 장면의 시트 한 장만 종이 크기로 깔아 찍습니다. 화면의 나머지는 인쇄에서만 감춥니다.",
    },
    {
      id: "page-finish-scene-video",
      route: P,
      page: "finish",
      anchor: "finish-scene-video",
      title: "씬 영상 — 밖에서 뽑아 온 것도 여기로",
      body: "«씬 영상» 선반에 «영상 불러오기» 나 끌어다 놓기로 등록하면 그 장면의 씬 영상으로 붙습니다. 어느 컷의 것인지는 컷 카드에서 넣어야 알 수 있습니다.",
    },
    {
      id: "page-finish-cut-videos",
      route: P,
      page: "finish",
      anchor: "finish-cut-videos",
      title: "컷 영상",
      body: "컷 카드 안에 등록한 영상을 장면별로 모아 봅니다. 씬 영상은 위 선반이 이미 보여 주므로 여기는 컷 것만입니다.",
    },
    {
      id: "page-finish-exit",
      route: P,
      page: "finish",
      anchor: "project-finish",
      title: "프로젝트 목록으로",
      body: "«프로젝트 목록으로» 는 저장하고 보드로 나갑니다. 이미 자동 저장되고 있으니 안 누르고 위 띠로 나가도 잃는 것은 없습니다.",
    },
  ],
};

const SETTINGS: Tutorial = {
  id: "page-settings",
  kind: "page",
  page: "settings",
  title: "설정 — 작업 환경",
  summary: "폴더 · API 키 · 작업별 모델 · 생성기 · 엔진 · 로라 · 문구를 정하는 화면입니다. 전부 이 기기에만 저장됩니다.",
  steps: [
    {
      id: "page-settings-profile",
      route: "/settings",
      page: "settings",
      anchor: "settings-profile",
      title: "프롬프트 작성 프로필",
      body: "Claude(긴 글과 판단) 와 GPT(구조와 형식) 카드 중 하나가 «선택됨» 입니다. 아래 API 키와 작업별 모델이 이 선택을 따라갑니다.",
    },
    {
      id: "page-settings-language",
      route: "/settings",
      page: "settings",
      anchor: "settings-language",
      title: "언어 · 튜토리얼",
      body: "한국어(기본) · 영어 · 일본어 · 중국어 중 하나를 고르면 화면 문구와 튜토리얼이 그 언어로 바뀝니다. 튜토리얼은 같은 자리의 스위치로 켜고 끕니다.",
    },
    {
      id: "page-settings-folders",
      route: "/settings",
      page: "settings",
      anchor: "settings-folders",
      title: "폴더",
      body:
        "«기본 저장 폴더» 하나만 정하면 «프롬프트 문구 폴더» 와 «포즈 프리셋 폴더» 는 그 안에서 갈라집니다. 각각 «다른 곳으로» 로 따로 두거나 «기본 자리로» 되돌립니다. 문구 폴더의 md 파일은 앱 밖 편집기로도 고칠 수 있습니다.",
    },
    {
      id: "page-settings-api-keys",
      route: "/settings",
      page: "settings",
      anchor: "settings-api-keys",
      title: "API 키",
      body:
        "Claude · OpenAI 키를 붙여넣고 «저장». 저장한 뒤에는 «저장됨 ···끝 네 자리» 만 보이고 «연결 확인» «지우기» 가 뜹니다. 키는 앱 설정 폴더에 파일로 저장되고 호출도 앱 안에서 합니다. 두 곳 모두 결제 수단 등록이 필요합니다.",
    },
    {
      id: "page-settings-auto-unfold",
      route: "/settings",
      page: "settings",
      anchor: "settings-auto-unfold",
      title: "전개도 자동 6면 커팅",
      body:
        "장소 카드에 전개도가 들어오면 여섯 면의 경계·비율·회색 여백을 검사합니다. 빠진 면이나 찌그러짐이 의심되면 자동 커팅을 멈추고 원본을 남깁니다. 회색 벽도 여백으로 판단될 수 있으니 경고를 보고 가위 → «전개도 6면» 에서 선을 직접 맞추세요. 필요하면 이 설정을 끄고 수동으로 자릅니다.",
    },
    {
      id: "page-settings-lora",
      route: "/settings",
      page: "settings",
      anchor: "settings-lora",
      title: "로라 (엔진별로 찾고 받기)",
      body:
        "엔진마다 폴더가 갈립니다 — 로라는 학습한 모델에 묶여 있어 엔진이 다르면 로딩이 통째로 실패합니다. 검색 칸에 «dance» «anime style» 처럼 적고 «찾기», 결과에서 «받기». 받아 둔 목록에서 «세기»(1 이 원래) 와 «기본»(따로 고르지 않은 생성에 들어감)을 정합니다. 브라우저로 받은 파일은 «파일 고르기» 로 들이고, Civitai API 키·허깅페이스 토큰을 넣어 두면 로그인이 필요한 것도 앱이 대신 받습니다.",
    },
    {
      id: "page-settings-magnific",
      route: "/settings",
      page: "settings",
      anchor: "settings-magnific",
      title: "마그니픽 (MCP 로 끝까지 뽑기)",
      body:
        "«연결» 을 누르면 브라우저가 열리고 코드를 넣습니다. 연결되면 «한 번에 뽑기» 에 «마그니픽 — 끝까지 뽑기» 가 생깁니다 — 사람 손 없이 인물 시트부터 씬 영상까지, 다만 건당 과금. 여태 쓰던 «생성기를 차려 놓기»(창에서 직접 뽑는 길)는 그대로입니다. «연결 확인» «연결 끊기» 도 여기.",
    },
    {
      id: "page-settings-local",
      route: "/settings",
      page: "settings",
      anchor: "settings-local-engines",
      title: "로컬 모델 (그림·영상·음악)",
      body:
        "GPU·빈 자리를 보고 설치 여부를 정하고 «설치» 또는 «가중치 미리 받기» 를 누릅니다. 공통 «정밀도» 외에 각 생성 모델의 «모델별 정밀도» 를 따로 고를 수 있습니다. «공통 설정 따르기» 와 «자동 — 이 GPU 에 맞춰» 는 다르며, 그 모델이 지원하는 값만 나옵니다. «다음 생성 예상» 을 확인하세요. 메모리를 줄여도 더 빨라지는 것은 아니며, «워커 내리기» 는 상주 모델의 RAM·VRAM을 비웁니다.",
    },
    {
      id: "page-settings-upscale",
      route: "/settings",
      page: "settings",
      anchor: "settings-upscale",
      title: "업스케일 엔진",
      body:
        "«기본 목표 크기» 와 «기본» 엔진을 정하면 가위 편집 창 · 6면 세트 카드 · 파노라마 탭의 «업스케일» 이 그것을 씁니다. ComfyUI 와 무관한 고정 환경이고, 바깥 ComfyUI 워크플로를 «외부 엔진» 으로 잡을 수도 있습니다. «작업 후 워커 유지» 를 켜 두면 다음 장이 빠릅니다.",
    },
    {
      id: "page-settings-docs",
      route: "/settings",
      page: "settings",
      anchor: "settings-prompt-docs",
      title: "가이드 문서 관리",
      body:
        "모델 · 플랫폼 · 기법 · 요청문 네 갈래의 md 문서를 보고 고칩니다. «전체 내보내기» 로 json 한 장에 담고 «불러오기» 로 되살립니다. 앱 기본 문구가 바뀌면 손대지 않은 사본만 자동으로 갈아 끼우고, 고쳐 둔 것은 «기본값으로» 를 눌러야 받습니다.",
    },
    {
      id: "page-settings-task-models",
      route: "/settings",
      page: "settings",
      anchor: "settings-task-models",
      title: "작업별 모델",
      body:
        "«사용할 제공자» 를 고르면 그 제공자의 표가 뜹니다. 작업마다 모델(Sonnet 5 — 균형 · Opus 5 — 품질 우선 · Haiku 4.5 — 빠르고 저렴, GPT-5.6 Terra · Sol · Luna)과 추론 노력(생각 없이 · 조금 · 보통 · 깊이 · 아주 깊이)을 둡니다. 제공자마다 따로 저장되어 바꿔 가며 견줘도 앞 설정이 남습니다. «기본값» 으로 되돌립니다.",
    },
    {
      id: "page-settings-nav",
      route: "/settings",
      page: "settings",
      anchor: "nav-ai-ready",
      title: "위 띠의 «AI 최적화 준비됨»",
      body: "키가 저장되어 있으면 «AI 최적화 준비됨», 없으면 «AI 최적화 필요» 입니다. 카드의 «프롬프트 작성» «이미지 분석» 단추가 이 상태를 따라 켜집니다.",
    },
  ],
};

const BGM: Tutorial = {
  id: "page-bgm",
  kind: "page",
  page: "bgm",
  title: "BGM 프로젝트",
  summary: "Suno · 로컬 MiniMax Music 용 곡 스타일과 가사를 만들고, 뽑은 곡을 곡별로 정리합니다. 영상 프로젝트와 따로 삽니다.",
  steps: [
    {
      id: "page-bgm-project",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-project-add",
      title: "프로젝트 추가 · 지우기",
      body:
        "«프로젝트 추가» 로 이름을 적어 «만들기». 곡은 «<저장 폴더>/BGM/곡/<BGM 프로젝트>/» 에 들어갑니다. 휴지통은 기록만 지우고 음원 파일은 남깁니다 — 다른 컷이 그 곡을 타임라인에 깔고 있을 수 있어서요.",
    },
    {
      id: "page-bgm-track",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-track-add",
      title: "곡 추가",
      body: "왼쪽 목록의 «+ 곡 추가» 로 곡을 만들고 «곡 이름» 과 «어느 장면에 쓸지» 를 적습니다.",
    },
    {
      id: "page-bgm-chips",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-chips",
      title: "분위기 · 장르 · 악기 · 보컬 · «시대 · 질감» · 프로덕션 · 곡 구조",
      body: "칩을 켜면 그 낱말이 그대로 스타일 문장과 가사 틀이 됩니다. «곡 구조» 는 고른 차례대로 구간이 만들어지고, 로컬 모델은 길이(초)보다 이 구간 수를 따릅니다.",
    },
    {
      id: "page-bgm-tempo",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-tempo-length",
      title: "템포 · 길이",
      body: "«템포 (BPM)» «길이 (초)» 는 비우면 자동입니다. 로컬 모델은 가사의 구조 태그가 길이를 정합니다.",
    },
    {
      id: "page-bgm-tool",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-tool",
      title: "생성 도구",
      body: "Suno 처럼 밖에서 뽑는 도구는 여기서 프롬프트까지, 로컬 모델(MiniMax Music 등)은 아래에서 파일까지 나옵니다.",
    },
    {
      id: "page-bgm-instrumental",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-instrumental",
      title: "가사 없는 연주곡",
      body:
        "켜면 가사 없이 연주로만 만들고 «스타일 · 가사 뽑기» 는 구간 태그만 채웁니다. 꺼져 있는데 가사 없이 답이 오면 «연주곡이 아닌데 가사 없이 왔습니다» 알림이 뜹니다 — 그때는 스타일 칸의 «instrumental» 도 지우세요.",
    },
    {
      id: "page-bgm-write",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-write",
      title: "스타일 · 가사 뽑기 · 규칙 조립 · LLM 요청문",
      body:
        "«스타일 · 가사 뽑기» 는 설정에서 고른 모델로 곡 스타일 두 칸과 가사 두 칸을 받습니다(가사는 온 것만 덮어씀). «규칙 조립» 은 API 없이, «LLM 요청문» 은 복사해 밖에서. 이미 적어 둔 것이 있으면 덮어쓸지 묻습니다.",
    },
    {
      id: "page-bgm-panels",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-style-panels",
      title: "곡 스타일 · 가사 · 제외할 스타일",
      body:
        "«곡 스타일 (한글)» «Style (생성기에 넣는 칸)» 과 «가사 (한글)» «Lyrics (생성기에 넣는 칸)» — Suno v6 의 Style(1,000자) · Lyrics(5,000자) 두 칸과 같습니다. 한도를 넘기면 칸 아래에 «뒤가 잘립니다» 가 뜹니다. «제외할 스타일» 은 네거티브가 아니라 Suno 의 Exclude Styles 이고, 로컬 모델에는 «avoid …» 로 붙습니다.",
    },
    {
      id: "page-bgm-history",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-history",
      title: "받아 둔 곡 스타일",
      body: "받거나 조립할 때마다 쌓이고 «되돌리기» 로 앞 판으로 갑니다 — 인물·장소 카드와 같은 선반입니다.",
    },
    {
      id: "page-bgm-local",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-local-generate",
      title: "로컬 모델로 바로 뽑기",
      body:
        "«생성 도구» 에서 로컬 모델을 골랐고 설치되어 있으면 «바로 뽑기» 가 켜집니다. 영문 스타일과 가사를 보내고(태그 어휘가 영어), 곡은 «작업» 서랍의 줄에 서서 몇 분 뒤 아래 목록에 파일로 옵니다.",
    },
    {
      id: "page-bgm-tracks",
      route: "/bgm",
      page: "bgm",
      anchor: "bgm-tracks-list",
      title: "뽑은 곡 목록",
      body: "곡마다 재생기와 «목록에서 뺍니다(폴더의 파일은 그대로 둡니다)» 단추가 있습니다. 여기 있는 곡을 구도잡기 «노래» 칸의 «BGM에서 고르기» 가 그대로 씁니다.",
    },
    {
      id: "page-bgm-to-planner",
      route: "/bgm",
      page: "bgm",
      title: "뮤직비디오로 이어 가기",
      body:
        "곡을 타임라인에 올리는 자리는 구도잡기 «타임라인» 탭의 «노래» 칸입니다. 거기서 «노래 길이로» 타임라인을 맞추고 구간을 나누면, 그 경계가 «레퍼런스 영상» 나눠 뽑기의 자르는 자리가 됩니다.",
    },
  ],
};

/*
  ── 화면 하나에 갈래 여럿 ──────────────────────────────────────────────────
  

  캐릭터 화면에서 여는 창(계보·시트 합성·생성 결과 선반·이미지 편집)은 저마다 손잡이가 열 몇 개씩
  됩니다. 한 갈래에 다 넣으면 서른 걸음이 넘어 어디까지 봤는지 잊습니다. 그래서 창마다 갈래를
  하나씩 두고, 위 띠의 «이 페이지 기능» 에 나란히 세웁니다.
*/

const PAGE_LINEAGE: Tutorial = {
  id: "page-lineage",
  kind: "page",
  page: "characters",
  // 같은 창이 인물·장소·에셋·컷 어디서나 열립니다(규칙 1) — 목록에도 그렇게 섭니다.
  pages: ["characters", "scenes", "finish"],
  title: "변형 · 다른 원본 · 계보",
  summary: "인물 패널의 계보 카드를 열고·떨구고·지우는 법, 변형 창 안의 칸, «다른 원본» 상자, 구워 둔 시트 다루기까지.",
  steps: [
    {
      id: "page-lineage-panel",
      route: P,
      page: "characters",
      anchor: "character-panel",
      title: "패널의 이름 칸과 지우기",
      body: "패널 하나가 인물(장소·에셋) 하나입니다. 맨 위 이름 칸에 적는 이름이 곧 저장 폴더의 이름이자 파일 앞부분이라, 고치면 폴더와 «옛 이름_» 으로 시작하는 파일이 전부 따라갑니다. 오른쪽 빨간 X 는 카드만 빼는 것이 아니라 그 인물 폴더를 통째로 — 변형·애셋·시트까지 — 지웁니다.",
      action: "해 볼 것: 맨 위 이름 칸에 인물 이름을 적으세요.",
      why: "«저장 폴더의 원본 파일도 함께 지워집니다» 를 한 번 묻습니다. 파일을 남기면 폴더를 다시 읽을 때 지운 것이 되살아나기 때문에, 화면에서 지우는 것이 곧 파일을 지우는 것입니다.",
    },
    {
      id: "page-lineage-collapse",
      route: P,
      page: "characters",
      anchor: "character-panel",
      title: "접기 — 한 줄 요약",
      body: "이름 왼쪽 화살표를 누르면 패널이 한 줄로 줄어듭니다. 접히면 대표 그림 하나와 «변형 3 · 다른 원본 1 · 애셋 2 · 시트 4» 같은 요약만 남고, 아무것도 없으면 «아직 비어 있음» 이라고 뜹니다. 그 요약 줄 자체가 단추라 누르면 다시 펼쳐집니다.",
      action: "해 볼 것: 이름 왼쪽 화살표를 눌러 접었다가, 요약 줄을 눌러 다시 펴 보세요.",
      why: "인물이 셋만 넘어가도 무엇이 있는지 보려고 한없이 스크롤해야 했습니다. 접힘은 이 컴퓨터에만 기억하고 자료는 건드리지 않습니다.",
    },
    {
      id: "page-lineage-card",
      route: P,
      page: "characters",
      anchor: "lineage-card",
      title: "계보 카드 — 누르면 열리고, 떨구면 붙습니다",
      body: "왼쪽이 원본, 오른쪽으로 곡선을 타고 갈라진 것이 변형입니다. 카드 그림을 누르면 그 판의 편집 창이 열립니다 — 원본이면 인물 카드, 변형이면 변형 창입니다. 밖에서 뽑아 온 그림 파일을 카드 위로 끌어오면 테두리가 강조색으로 바뀌고, 놓는 순간 그 판의 생성 이미지로 저장됩니다.",
      action: "해 볼 것: 변형 카드의 그림을 눌러 변형 창을 열어 보세요.",
      why: "카드에 바로 떨구는 것이 창을 열지 않고 그림을 붙이는 유일한 길입니다. 계보에서 «이 판» 이 눈앞에 있는데 창을 열고 한참 내려가 «생성 결과 이미지» 를 찾는 것이 이상해서 생겼습니다.",
    },
    {
      id: "page-lineage-variation-model",
      route: P,
      page: "characters",
      anchor: "variation-model",
      title: "변형 창 — 이 변형만의 이미지 모델",
      body: "변형 창 머리에는 이름 칸(«겨울 외투», «밤 장면» 처럼)과 이미지 모델 고르는 칸이 나란히 있습니다. 여기서 고른 모델의 문법으로 이 변형의 프롬프트가 지어집니다. 인물 카드에서 고른 «이미지 모델» 과는 따로라, 변형 하나만 다른 생성기로 뽑을 때 여기서 바꿉니다.",
      action: "해 볼 것: 모델 목록을 열어 어떤 것이 있는지 보세요.",
    },
    {
      id: "page-lineage-variation-images",
      route: P,
      page: "characters",
      anchor: "variation-parent-images",
      title: "부모의 그림을 눌러 레퍼런스로",
      body: "«이 캐릭터의 생성 이미지·레퍼런스 — 클릭해 레퍼런스에 추가» 줄에는 부모가 가진 그림이 모두 늘어섭니다. 타일을 누르면 이 변형의 레퍼런스로 들어가 «추가됨» 이 붙고, 다시 누르면 빠집니다(파일은 폴더에 그대로 남습니다). «정체성 기준» 이라고 적힌 타일만은 빠지지 않습니다 — 바꾸려면 다른 그림 오른쪽 위의 ★ 을 누르세요.",
      action: "해 볼 것: 타일 하나를 눌러 «추가됨» 이 붙는지 보고, 다시 눌러 빼 보세요.",
      why: "정체성 기준을 빼면 다른 사람이 됩니다. 그래서 바꾸는 것만 되고 빼는 것은 막혀 있습니다.",
    },
    {
      id: "page-lineage-variation-crop",
      route: P,
      page: "characters",
      anchor: "card-image-crop",
      title: "변형 창의 가위 — 잘라낸 칸은 부모에게",
      body: "변형 창의 그림에도 가위가 붙습니다. 여기서 자른 칸과 지운 판은 «인물_변형_칸이름_자름_001» 로 저장되어 부모의 생성 이미지 목록으로 올라갑니다. 그래서 어느 변형에서든 그 조각을 다시 레퍼런스로 집을 수 있습니다.",
      action: "해 볼 것: 그림에 마우스를 올려 오른쪽 위 가위 자리만 확인하세요.",
      why: "배경 변형 창에 파노라마나 전개도가 들어오면 여섯 면이 저절로 잘려 같은 자리로 갑니다. 설정의 «전개도 자동 6면 커팅» 을 꺼 두면 안 돕니다.",
    },
    {
      id: "page-lineage-variation-remove",
      route: P,
      page: "characters",
      anchor: "lineage-variation-remove",
      title: "변형 지우기 — 자식이 있으면 다릅니다",
      body: "변형 카드에 마우스를 올리면 오른쪽 위에 X 가 뜹니다(원본 카드에는 없습니다). 이 판에서 갈라진 자식 변형이 없으면 «저장 폴더의 원본 파일도 함께 지워집니다» 를 묻고 그 판의 파일까지 지웁니다. 자식이 있으면 그 그림이 자식의 정체성 기준이라 파일은 남기고, 자식들을 한 단계 위로 올려 붙입니다.",
      action: "해 볼 것: 변형 카드에 마우스를 올려 오른쪽 위 X 가 뜨는 자리만 확인하세요. 되돌릴 수 없으니 여기서는 보기만 합니다.",
    },
    {
      id: "page-lineage-alternates",
      route: P,
      page: "characters",
      anchor: "lineage-alternates",
      title: "«다른 원본» — 같은 인물의 다른 모습",
      body: "계보 바로 아래 상자입니다. 어린 시절·노인처럼 같은 인물의 다른 모습을 담고(장소면 계절·시대), 원본마다 제 변형을 따로 가집니다. 비어 있으면 «아직 다른 원본이 없습니다» 라고만 뜨고, 상자 끝의 «캐릭터 생성»(장소면 «배경 생성»)을 누르면 새 원본이 생기면서 바로 편집 창이 열립니다.",
      action: "해 볼 것: 상자의 설명 줄을 읽고, 지금 다른 원본이 몇 개 있는지 확인하세요.",
      why: "여기서 만든 것도 전부 주인 폴더 안에 «주인_원본이름_번호» 로 들어갑니다 — 폴더는 인물당 하나입니다.",
    },
    {
      id: "page-lineage-alternate-mini",
      route: P,
      page: "characters",
      anchor: "character-variation",
      title: "원본마다 작은 계보",
      body: "원본 이름 줄 아래에는 큰 계보와 똑같이 생긴 작은 계보가 붙습니다. 카드 열기 · «이 카드에서 변형» · 변형 X · 그림 떨구기 네 가지가 큰 계보와 똑같이 됩니다. 여기서 만든 변형은 «주인_원본이름_변형» 이라는 이름으로 역시 주인 폴더 안에 들어갑니다.",
      action: "해 볼 것: 작은 계보에도 «이 카드에서 변형» 단추가 있는지 확인하세요.",
      why: "다른 원본은 한 단계까지만입니다. 더 깊어지면 폴더 하나에 «냥이_어린시절_아기_…» 가 끝없이 붙어 어느 것이 주인인지 알 수 없어집니다.",
    },
    {
      id: "page-lineage-alternate-name",
      route: P,
      page: "characters",
      anchor: "lineage-alternate-name",
      title: "원본 이름 칸과 X",
      body: "이름을 적고 커서가 칸 밖으로 나가는 순간 파일 앞부분(«숲_겨울_…»)이 새 이름을 따라 바뀝니다. 주인 변형·보유 애셋·형제 원본과 앞부분이 겹치면 거부하고 이름을 되돌립니다. 오른쪽 X 는 그 원본의 레퍼런스·생성 이미지·변형 파일만 지우고 주인과 주인의 변형은 그대로 둡니다 — 원본 카드에는 X 가 없어 지우는 길은 이것뿐입니다.",
      action: "해 볼 것: 원본 이름 칸에 «어린 시절» 처럼 적으세요.",
      why: "글자마다 파일을 바꾸면 «어», «어린» 으로 시작하는 파일이 줄줄이 생기고 확인 창이 계속 뜹니다. 그래서 커서가 빠질 때 한 번만 따라갑니다.",
    },
    {
      id: "page-lineage-alternate-editor",
      route: P,
      page: "characters",
      anchor: "lineage-alternate-editor",
      title: "원본 편집 창 — 인물 카드 그대로",
      body: "원본 카드를 누르면 뜨는 창입니다. 역할·키·프로필·분석·프롬프트 칸이 인물 카드와 똑같이 들어 있습니다 — 어린 시절도 인물이니까요. «분석 가져오기» 목록에는 주인과 형제 원본의 분석이 실려, 같은 인물의 설명을 다시 적지 않아도 됩니다.",
      action: "해 볼 것: 원본 카드를 눌러 편집 창을 열어 보세요.",
      why: "닫기(X·ESC·바깥 클릭)가 곧 저장입니다. 다만 이름도 그림도 아무것도 안 적은 원본은 닫는 순간 지워집니다 — 빈 «이름 없는 원본» 이 쌓이지 않게.",
    },
    {
      id: "page-lineage-sheet",
      route: P,
      page: "characters",
      anchor: "lineage-sheet-tile",
      title: "제작한 시트 타일",
      body: "구워 둔 6000×6000 시트가 여기 쌓입니다. 그림을 누르면 화면 가득 크게 보고, 마우스를 올리면 네 귀퉁이에 단추가 뜹니다 — 왼쪽 위는 «복사»(클립보드로)와 «마그니픽으로»(캔버스에 이미지 노드로, 파일 이름 유지), 왼쪽 아래는 «폴더 열기»(탐색기에서 그 파일을 집어 줍니다). 오른쪽 아래 연필은 그 판의 배치 기록을 시트 창에 도로 실어 열고, 오른쪽 위 X 는 목록에서 빼면서 폴더의 png 파일도 지웁니다.",
      action: "해 볼 것: 시트 그림을 눌러 크게 열어 보세요. «마그니픽으로» 는 밖으로 나가는 길이니 자리만 봐 두세요.",
      why: "배치 기록이 없는 옛 시트에서는 연필이 아예 눌리지 않습니다 — 무엇을 어디에 놓았는지가 안 남아 있어 다시 열 수가 없습니다. 그때는 새로 만드세요.",
    },
    {
      id: "page-lineage-sheet-name",
      route: P,
      page: "characters",
      anchor: "lineage-sheet-name",
      title: "이 판의 이름",
      body: "시트 밑 칸에 적는 이름은 «어느 판인지» 알아보라고 붙이는 이름표입니다 — «정면 3면», «표정 12칸» 처럼. 파일 이름은 바뀌지 않고, 그 아래 회색 줄이 진짜 파일 이름과 규격을 그대로 보여 줍니다. 시트가 여러 장 쌓이면 이름을 안 붙인 것은 나중에 구분이 안 됩니다.",
      action: "해 볼 것: 시트 밑 이름 칸에 «정면 3면» 처럼 적으세요.",
    },
  ],
};

const PAGE_SHEET: Tutorial = {
  id: "page-sheet",
  kind: "page",
  page: "characters",
  // 같은 창이 인물·장소·에셋·컷 어디서나 열립니다(규칙 1) — 목록에도 그렇게 섭니다.
  pages: ["characters", "scenes", "finish"],
  title: "시트 합성 창",
  summary: "왼쪽 그림을 칸으로 놓고 배치도·규격을 잡아 한 장으로 굽는 창입니다. 칸 하나를 옮기고·갈아 끼우고·이름 붙이는 것까지 하나씩.",
  steps: [
    {
      id: "page-sheet-close",
      route: P,
      page: "characters",
      anchor: "sheet-close",
      title: "이 창이 하는 일 · «닫기»",
      body: "인물의 전신·얼굴·표정·색 기준을 한 장에 모아 영상 모델에 물리는 시트를 여기서 짭니다. 왼쪽은 «넣을 그림»·배치도·규격이고, 가운데 흰 판이 시트 그 자체입니다. 머리줄 오른쪽 X(«닫기»)는 창을 그대로 닫습니다 — 놓은 칸은 배치도에 곧바로 저장되니 사라지지 않지만, 굽지 않았으면 시트 파일은 아직 없습니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 창이 닫히고 튜토리얼도 여기서 끊깁니다.",
      why: "칸을 놓고 옮기는 것은 바로 배치도에 올라갑니다. 한 장짜리 그림 파일을 만드는 것은 «시트 제작» 뿐입니다.",
    },
    {
      id: "page-sheet-sources",
      route: P,
      page: "characters",
      anchor: "sheet-source-groups",
      title: "왼쪽 «넣을 그림»",
      body: "아직 시트에 안 놓은 그림만 «원본» · «변형 · {변형 이름}» · «다른 원본» · «보유 에셋» · «공용 에셋» 다섯 갈래로 모여 있습니다. 머리줄을 누르면 그 갈래가 접히고 다시 누르면 펼쳐지며, 오른쪽 숫자가 그 갈래의 장수입니다. 인물 그림과 소품이 한 줄에 섞이면 무엇을 집는지 알 수 없어 갈래를 나눠 둔 것입니다.",
      action: "해 볼 것: «원본» 머리줄을 눌러 접었다 펴 보세요.",
    },
    {
      id: "page-sheet-add",
      route: P,
      page: "characters",
      anchor: "sheet-source-tile",
      title: "타일을 누르면 칸이 됩니다",
      body: "그림 타일을 한 번 누르면 시트의 빈자리에 계단식으로 새 칸이 생깁니다. 칸 크기는 타일 밑에 적힌 «2048×2048» 같은 뽑힌 px 그대로이고, 시트보다 크면 비율을 지켜 줄이면서 알려 줍니다. 놓은 그림은 이 목록에서 빠지고, 칸을 빼면 다시 돌아옵니다.",
      action: "해 볼 것: 타일 하나를 눌러 시트에 놓으세요.",
      why: "그림을 뽑힌 크기 그대로 넣어야 6000 시트에 몇 장이 들어가는지 가늠이 됩니다. 예전처럼 전부 같은 크기로 들어가면 2048 짜리와 1024 짜리가 시트에서 구분되지 않습니다.",
    },
    {
      id: "page-sheet-face-set",
      route: P,
      page: "characters",
      anchor: "sheet-face-set",
      title: "6면 세트는 면 하나씩",
      body: "전개도에서 잘린 6면 세트는 낱장 여섯으로 흩어지지 않고 카드 한 장으로 접혀 있습니다. 시트에 놓을 것은 낱장이라, 카드의 셀 하나를 누르면 그 면만 시트에 놓입니다. 셀을 끌어 이미 놓인 칸 위에 떨구면 그 칸의 그림이 그 면으로 바뀝니다.",
      action: "해 볼 것: 6면 세트 카드가 있으면 셀 하나를 눌러 시트에 놓아 보세요.",
    },
    {
      id: "page-sheet-source-crop",
      route: P,
      page: "characters",
      anchor: "sheet-source-crop",
      title: "타일의 가위 — 자르기·지우기",
      body: "타일에 마우스를 올리면 오른쪽 아래에 가위가 뜹니다. 누르면 이 창 위에 «자르기·지우기» 창이 겹쳐 떠서, 얼굴만 잘라 내거나 손에 쥔 엉뚱한 물건을 둘레 색으로 덮을 수 있습니다. 저장한 파일은 이 인물의 생성 이미지가 되어 왼쪽 목록에 새 타일로 나타납니다 — 시트를 짜다 말고 나갔다 올 필요가 없습니다.",
      action: "해 볼 것: 타일에 마우스를 올려 가위 자리를 확인하세요.",
    },
    {
      id: "page-sheet-layouts",
      route: P,
      page: "characters",
      anchor: "sheet-layouts",
      title: "배치도 — 프로젝트 공용",
      body: "칸의 자리·크기·이름·규격이 «배치도» 이고, 그림이 아니라 틀이라 프로젝트 전체가 나눠 씁니다. 이름 왼쪽 동그라미를 누르면 그 배치도로 갈아타고(칸이 통째로 바뀌며 앞 배치도의 되돌리기 기록은 비워집니다), 이름 칸은 그 자리에서 고칩니다. 겹친 네모는 칸을 물려받는 복제, «새 배치도» 는 칸 없이 빈 채로 시작, 휴지통은 «「…」 배치도를 지울까요?» 를 물은 뒤 프로젝트 목록에서 뺍니다.",
      action: "해 볼 것: 배치도 이름 칸에 «전신 4칸» 처럼 이름을 적어 보세요.",
      why: "배치도를 지우면 그것을 쓰던 다른 인물에서도 사라집니다. 이미 구워 둔 시트 파일은 그대로 남습니다.",
    },
    {
      id: "page-sheet-size",
      route: P,
      page: "characters",
      anchor: "sheet-size-fields",
      title: "뽑을 규격 — «가로» · «세로»",
      body: "위 프리셋 셋 말고 «가로»·«세로» 를 직접 쳐서 512~12000 사이 아무 규격이나 만듭니다(↑↓ 키는 64씩). 규격은 캔버스 크기일 뿐이라 바꿔도 칸의 px 는 그대로이고, 밖으로 나간 칸만 안으로 밀려 들어옵니다.",
      action: "해 볼 것: «가로» 에 4096 을 쳐 보세요. 가로·세로를 오가는 동안은 한 동작이라 Ctrl+Z 한 번에 풀립니다.",
      why: "「4000」 은 4 → 40 → 400 → 4000 으로 네 번 올라옵니다. 매번 «치기 시작한 판» 에서 다시 맞추기 때문에, 4 를 쳤을 때 512 에 맞춰 줄어든 칸이 그대로 굳지 않습니다.",
    },
    {
      id: "page-sheet-board",
      route: P,
      page: "characters",
      anchor: "sheet-board",
      title: "가운데 흰 판이 시트입니다",
      body: "6000px 를 그대로 띄울 수 없어 긴 변을 720px 로 줄여 보여 줍니다 — 규격을 작게 잡으면 같은 px 의 칸이 화면에서 커 보이는 게 맞습니다. 칸이 아닌 흰 바닥을 누르면 고른 칸이 풀리고 왼쪽의 «고른 칸» 블록이 사라집니다. 왼쪽 그림을 끌어 빈 바닥에 떨구면 누르는 것과 달리 바로 그 자리에 새 칸이 생깁니다.",
      action: "해 볼 것: 흰 바닥을 한 번 눌러 고른 칸을 풀어 보세요.",
    },
    {
      id: "page-sheet-slot",
      route: P,
      page: "characters",
      anchor: "sheet-slot",
      title: "칸 옮기기 · 크기 바꾸기 · 그림 갈아 끼우기",
      body: "상자 전체가 이동 손잡이입니다 — 눌러 고르고 그대로 끌면 자리가 옮겨지며 시트 밖으로는 나가지 않습니다. 오른쪽 아래 모서리의 삼각형을 끌면 가로·세로가 바뀌고 최소 200px 까지만 작아집니다. 왼쪽 그림을 놓인 칸 위로 끌면 테두리가 하늘색으로 굵어지고, 떨구면 칸 크기는 그대로 둔 채 그림만 갈아 끼웁니다(프로필 글상자는 받지 않습니다).",
      action: "해 볼 것: 칸 하나를 끌어 옮기고, 오른쪽 아래 모서리를 잡아 크기를 바꿔 보세요.",
      why: "의상이 바뀌었을 때 시트를 처음부터 다시 놓지 않으려고 «칸 위에 떨구면 교체» 가 있습니다. 끌기 한 번이 되돌리기 한 판이라 Ctrl+Z 로 끌기 하나가 통째로 풀립니다.",
    },
    {
      id: "page-sheet-slot-label",
      route: P,
      page: "characters",
      anchor: "sheet-slot-label",
      title: "칸 이름표 — 상자 밖 위",
      body: "이름표를 한 번 누르면 그 칸이 고른 칸이 되고, 더블클릭하면 그 자리가 입력칸으로 바뀝니다. Enter·Escape 를 누르거나 딴 데를 누르면 끝납니다. 이름을 안 적으면 그림 이름이나 «칸 이름 없음»·«빈 칸»·«프로필» 로 보이고, 여기 적은 이름이 «칸 이름 굽기» 를 켰을 때 시트에 찍히는 글자입니다.",
      action: "해 볼 것: 이름표를 더블클릭해 «전신» 이라고 적어 보세요.",
      why: "이름표가 상자 안에 있으면 그림을 가립니다. 그래서 상자 밖 위에 두고, 칸이 시트 맨 위에 붙었을 때만 안으로 들어옵니다.",
    },
    {
      id: "page-sheet-slot-remove",
      route: P,
      page: "characters",
      anchor: "sheet-slot-remove",
      title: "«빼기» · 칸의 가위",
      body: "칸 왼쪽 아래 X(«빼기»)는 그 칸을 배치도에서 뺍니다 — 그림 파일은 그대로고 왼쪽 «넣을 그림» 목록으로 돌아오며, Ctrl+Z 로 되살립니다. 칸에 마우스를 올리면 오른쪽 위에 가위가 뜨는데, 그 칸의 그림으로 «자르기·지우기» 창을 열고 저장한 그림 중 첫 장이 이 칸에 바로 들어갑니다. 나머지 장도 이 인물의 생성 이미지로 남습니다.",
      action: "해 볼 것: 칸에 마우스를 올려 «빼기» 와 가위 자리를 확인하세요.",
    },
    {
      id: "page-sheet-selected",
      route: P,
      page: "characters",
      anchor: "sheet-selected",
      title: "«고른 칸» — 이름과 크기를 숫자로",
      body: "칸을 고르면 왼쪽에 «고른 칸» 블록이 생깁니다. «칸 이름» 은 보드의 이름표와 같은 값이고, «크기 (px)» 의 «가로»·«세로» 는 손잡이로 딱 떨어지게 잡기 어려운 값을 숫자로 넣는 자리입니다(최소 200px, ↑↓ 50씩). 프로필 글상자에는 «칸 이름» 칸이 없습니다 — 이름표 자리에 «프로필» 이 찍힙니다.",
      action: "해 볼 것: 칸 하나를 고르고 «가로» 에 1024 를 쳐 보세요.",
    },
    {
      id: "page-sheet-profile-font",
      route: P,
      page: "characters",
      anchor: "sheet-profile-font",
      title: "«프로필 글자» 크기",
      body: "«+ 프로필 글상자» 로 이름·나이·성격·말투를 찍는 칸을 만들면 왼쪽에 이 블록이 뜹니다. 슬라이더(20~200)와 그 밑 숫자칸은 프로필 칸의 글자만 바꿉니다 — 상자와 따로 움직여 상자를 넓혀도 글씨는 그대로입니다. 보드에서 프로필 칸에 마우스를 올리면 오른쪽 위에 «A-»·«A+» 가 떠서 같은 값을 4씩 줄이고 키웁니다.",
      action: "해 볼 것: 슬라이더를 끌어 글자를 키워 보세요. 끌기 한 번이 되돌리기 한 판입니다.",
      why: "상자를 넓혔더니 글씨까지 같이 커져 배치를 잡을 수 없었습니다. 그래서 둘을 떼어 놓았습니다.",
    },
    {
      id: "page-sheet-finish",
      route: P,
      page: "characters",
      anchor: "sheet-actions",
      title: "되돌리기 · 다시 하기 · 그리고 굽기",
      body: "«되돌리기»(Ctrl+Z)와 «다시 하기»(화면에는 안 적혀 있지만 Ctrl+Y·Ctrl+Shift+Z 도 같습니다)가 규격 변경과 칸 맞춤까지 한 판으로 묶어 풀고 되돌립니다. 바로 위에 주황 글씨 «규격 밖으로 나간 칸이 있습니다. 굽히면 그 부분은 잘립니다.» 가 떠 있으면, 규격을 키우거나 그 칸을 안으로 옮겨 없앤 뒤에 구우세요. 다 놓았으면 «6000 × 6000 시트 제작» 으로 한 장을 굽고, 이미 있는 시트를 고치러 들어왔으면 «다시 굽기 (이 시트를 바꿈)» 와 «새 판으로 저장» 중에 고릅니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 큰 한 장을 합성해 폴더에 넣느라 시간이 걸리고, 다 구우면 창이 닫힙니다.",
      why: "«다시 굽기» 는 옛 파일을 지우고 갈아 끼웁니다. «새 판으로 저장» 은 옛 시트를 그대로 둔 채 항목을 하나 더 만듭니다.",
    },
  ],
};

const PAGE_SHELF: Tutorial = {
  id: "page-shelf",
  kind: "page",
  page: "characters",
  // 같은 창이 인물·장소·에셋·컷 어디서나 열립니다(규칙 1) — 목록에도 그렇게 섭니다.
  pages: ["characters", "scenes", "finish"],
  title: "생성 결과 · 후보함 · 영상 선반",
  summary: "뽑아 온 그림과 영상을 들이는 세 선반 — 낱장 타일과 6면 세트, 업스케일, 합성 시트, 마그니픽 후보함과 가져오기, 영상 칸과 큰 화면.",
  steps: [
    {
      id: "page-shelf-thumb",
      route: P,
      page: "characters",
      anchor: "card-generated-images",
      title: "낱장 그림 — 눌러서 크게, Ctrl+C 로 복사",
      body: "«생성 결과 이미지» 는 밖(프리픽·컴피UI·마그니픽)에서 뽑아 온 그림을 들여 놓는 선반입니다. 썸네일을 누르면 그 한 장이 화면 가득 뜹니다 — 120px 타일로는 손가락이 몇 개인지 눈이 풀렸는지 알 수 없어서, 제대로 뽑힌 그림인지는 여기서 봅니다. 타일을 눌러 고른 채로 Ctrl+C(맥은 Cmd+C)를 누르면 그 그림이 클립보드에 담겨 LLM 창에 바로 붙여넣을 수 있습니다.",
      action: "해 볼 것: 낱장 그림 하나를 누르세요.",
    },
    {
      id: "page-shelf-corners",
      route: P,
      page: "characters",
      anchor: "card-generated-images",
      title: "썸네일 네 모서리 — 복사 · 폴더 열기 · 마그니픽으로",
      body: "썸네일에 마우스를 올리면 모서리마다 단추가 나타납니다. 왼쪽 위 «복사» 는 그 그림을 클립보드에 담아 LLM 창에 붙여넣게 하고, 왼쪽 아래 «폴더 열기» 는 그 파일이 든 저장 폴더를 파일이 잡힌 채로 탐색기에서 엽니다(폴더에 파일이 있을 때만 뜹니다). 아래 가운데 단추는 그 파일을 마그니픽 데스크톱 캔버스에 바로 붙여넣고 됐는지 안 됐는지를 알림으로 알려 줍니다. 위 가운데 별은 대표 이미지, 오른쪽 위 X 는 빼기, 오른쪽 아래 가위는 편집 창입니다.",
      action: "해 볼 것: 자리만 확인하세요. 아래 가운데를 누르면 마그니픽 데스크톱이 그 그림을 받습니다.",
      why: "네 모서리 규칙은 레퍼런스 스트립·생성 결과·합성 시트가 모두 같습니다. 한 군데만 다르면 어느 그림에서 무엇이 되는지 매번 짚어 봐야 합니다.",
    },
    {
      id: "page-shelf-lightbox",
      route: P,
      page: "characters",
      anchor: "shelf-lightbox-nav",
      title: "크게 보기 창 — 넘기기 · 픽셀 크기 · 닫기",
      body: "그림을 크게 열면 아래 줄에 이름과 함께 실제 픽셀 크기가 «4096 × 4096 (4.0K)» 처럼 뜹니다 — 업스케일이 정말 먹었는지, 4K 라고 믿고 있던 것이 진짜 4K 인지를 여기서 확인합니다. 6면 세트처럼 여러 장을 열었으면 좌우의 «이전 (←)» «다음 (→)» 로 넘기고 아래 «3 / 6 · ← →» 가 함께 갱신됩니다 — 키보드 ← → 로도 됩니다. «닫기 (Esc)» 단추나 Esc 키, 그림 밖 검은 바탕을 눌러도 닫힙니다.",
      action: "해 볼 것: «다음 (→)» 으로 한 장 넘기고 «닫기 (Esc)» 로 닫으세요.",
    },
    {
      id: "page-shelf-face-set",
      route: P,
      page: "characters",
      anchor: "shelf-face-set",
      title: "6면 세트 카드 — 여섯 면을 한 칸으로",
      body: "장소의 6면 전개도는 낱장으로 늘어놓지 않고 3×2 카드 하나로 묶입니다 — 여섯 장이 선반을 채우면 다른 그림이 안 보입니다. 카드를 누르면 정면부터 여섯 면이 크게 보기로 열리고 ←/→ 로 넘겨 봅니다. 아직 다 안 찬 세트는 이름 뒤에 «— N면 없음» 이 붙고 빈 칸에 «없음» 이 뜹니다. 오른쪽 위 X 는 «세트 빼기 — 여섯 면 파일이 모두 지워집니다» 를 물은 뒤 목록에서 빼고 저장 폴더의 여섯 원본 파일까지 지웁니다 — 낱장 하나만 빼는 길은 세트 카드에 없습니다.",
      action: "해 볼 것: 6면 세트 카드를 누르세요.",
    },
    {
      id: "page-shelf-upscale-run",
      route: P,
      page: "characters",
      anchor: "shelf-upscale",
      title: "세트 업스케일 — 여섯 장을 덮어씁니다",
      body: "업스케일 단추는 6면 세트 카드에만 붙습니다 — 낱장 한 장 키우기는 가위로 여는 편집 창의 «업스케일해서 저장» 으로 모아 두었습니다. 이 단추를 누르면 설정의 «기본» 엔진과 «기본 목표 크기» 로 여섯 면을 차례로 키워 **같은 파일 이름에 덮어씁니다** — 키우기 전 원본은 남지 않습니다. 도는 동안 카드에 «정면 업스케일 중 1/6» 처럼 어디까지 갔는지 뜨고, 한 번 시작하면 끝날 때까지 취소할 수 없습니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 여섯 장이 차례로 커지며 같은 이름에 덮어써지고, 도중에 멈출 수 없습니다.",
    },
    {
      id: "page-shelf-upscale-menu",
      route: P,
      page: "characters",
      anchor: "shelf-upscale",
      title: "업스케일 ▾ — 엔진과 목표 크기 고르기",
      body: "단추 옆 «▾» 를 누르면 이번 한 번만 쓸 목표 크기와 엔진을 고르는 메뉴가 열립니다. 위 «목표 크기» 줄에서 2K · 4K 처럼 뽑을 긴 변을 고르는데, 앱이 원본의 긴 변을 실제로 재서 그 엔진 배율로는 거기까지 못 간다고 판단하면 숫자 뒤에 «*» 를 붙이고 «이 엔진에서는 여기까지 진짜로 못 키웁니다 — 늘린 그림이 됩니다» 라고 말해 줍니다. 아래 «엔진 — 누르면 바로 돌립니다» 줄에는 설치된 엔진이 «기본» · «늘리기» · «실험» 딱지와 함께 서 있고, 엔진 이름을 누르는 것이 곧 시작입니다.",
      action: "해 볼 것: «업스케일 ▾» 를 눌러 «목표 크기» 만 골라 보세요. 아래 엔진 줄은 누르는 순간 바로 돌기 시작합니다.",
      why: "«4K 로 키웠다» 고 믿었는데 사실은 늘리기였던 일이 있어서, 고르기 전에 숫자로 미리 말하게 했습니다.",
    },
    {
      id: "page-shelf-sheets",
      route: P,
      page: "characters",
      anchor: "card-generated-images",
      title: "제작한 시트 — 판마다 이름을 답니다",
      body: "선반 아래 보라색 상자는 모델이 뽑아 준 그림이 아니라 **그것들을 이어 붙여 우리가 만든** 6000×6000 시트입니다. 썸네일을 누르면 화면 가득 떠서 128px 로는 보이지 않던 칸들을 확인할 수 있습니다. 그 아래 «이 판의 이름» 칸에 «겨울 의상» · «부상 상태» 처럼 적어 두면 여러 판 중 무엇인지 나중에 알아봅니다 — 파일 이름은 그대로 두고 사람이 부를 이름만 붙는 것입니다. 타일에도 같은 모서리 규칙으로 복사 · 빼기(저장 폴더의 원본 파일도 함께) · 가위가 붙습니다 — 정작 칸을 잘라내야 할 대상이 이 시트입니다.",
      action: "해 볼 것: 시트 아래 «이 판의 이름» 칸에 «겨울 의상» 처럼 적으세요.",
    },
    {
      id: "page-shelf-inbox",
      route: P,
      page: "characters",
      anchor: "inbox-panel",
      title: "마그니픽에서 온 것 — 후보함",
      body: "화면 위 띠는 마그니픽 동기화 폴더로 내려온 그림·영상을 모아 두는 후보함입니다. 머리줄을 누르면 «마그니픽에서 온 것 N개 — 쓸 것만 채택하세요» 와 함께 타일이 펼쳐지고, 다시 누르면 «눌러서 펼치기» 한 줄로 접혀 «이 탭 것» · «다른 탭 것 N개» 숫자만 남습니다. 오른쪽 «숨긴 것 N개 되살리기» 는 숨김 기록을 통째로 지워, 우리가 보냈다가 되돌아온 그림까지 목록에 다시 올립니다. «후보함 열기» 는 프로젝트의 magnific/ 폴더를 탐색기로 엽니다 — 선반 머리의 «마그니픽 후보함» 과 같은 곳으로 가는 두 번째 문입니다.",
      action: "해 볼 것: 후보함 머리줄을 눌러 펼치세요.",
    },
    {
      id: "page-shelf-inbox-zoom",
      route: P,
      page: "characters",
      anchor: "shelf-inbox-zoom",
      title: "후보 타일 — 채택하기 전에 크게 보기",
      body: "타일 몸통을 누르면 «고른 것» 이 되어 테두리가 보라색으로 바뀌고, 오른쪽 위 «크게 보기» 는 고르지 않은 채 그 한 장만 화면 가득 띄웁니다. 176px 타일로는 A컷·B컷·C컷 중 어느 것이 나은지 가를 수 없어서, 누구 것인지 정하기 전에 들르는 자리입니다. 확인한 뒤 타일 아래 «누구 것?» 에서 인물·장소·컷·장면을 골라 채택합니다.",
      action: "해 볼 것: 후보 타일 오른쪽 위의 «크게 보기» 를 누르세요.",
    },
    {
      id: "page-shelf-import-find",
      route: P,
      page: "characters",
      anchor: "shelf-import-search",
      title: "마그니픽에서 가져오기 — 찾기",
      body: "선반 머리의 «가져오기» 를 누르면 마그니픽 계정에 **이미 만들어 둔** 결과를 골라 오는 창이 열립니다 — 다시 뽑는 것이 아니라 있는 것을 끌어오는 길이라 요금이 더 들지 않습니다. 오른쪽 위 «프롬프트로 찾기» 칸에 그때 쓴 프롬프트의 낱말을 적으면 그 글이 든 것만 걸러집니다(Enter 로도 바로 찾습니다). 옆의 «찾기» 는 목록을 처음부터 다시 불러옵니다. 아무것도 안 가져올 거면 맨 오른쪽 × 로 닫습니다.",
      action: "해 볼 것: «프롬프트로 찾기» 칸에 낱말을 하나 적으세요.",
    },
    {
      id: "page-shelf-import-take",
      route: P,
      page: "characters",
      anchor: "shelf-import-grid",
      title: "결과 타일 — 눌러서 가져오기",
      body: "격자의 타일 하나를 누르면 그 결과를 이 프로젝트 폴더로 내려받아 «인물_번호» 우리 이름으로 저장하고, 카드의 대표 이미지로 붙인 뒤 창이 닫힙니다. 받는 동안 타일이 흐려지고, 끝나면 «마그니픽에서 가져왔습니다» 알림에 저장된 이름이 함께 뜹니다. 마그니픽에 연결되어 있지 않으면 타일 대신 «설정 → 마그니픽에서 «연결» 을 눌러 주세요» 만 보입니다.",
      action: "해 볼 것: 자리만 확인하세요. 타일을 누르면 그 그림을 내려받아 이 카드의 대표 이미지로 붙이고 창이 닫힙니다.",
    },
    {
      id: "page-shelf-video",
      route: P,
      page: "characters",
      anchor: "finish-scene-video",
      title: "영상 선반 — 재생 · 대표 · 폴더 · 지우기",
      body: "밖에서 뽑아 온 mp4 를 «영상 불러오기» 나 끌어다 놓기로 넣으면 칸마다 재생기가 서서 그 자리에서 재생·일시정지·탐색·소리 조절을 합니다. 왼쪽 위 ★ 는 그 영상을 이 장면·컷의 대표로 세웁니다 — 노란 테두리가 둘리고 이름 앞에 ★ 가 붙으며, 대표는 늘 하나뿐이라 다른 것을 누르면 그쪽으로 옮겨 가고 같은 것을 다시 누르면 «대표에서 내립니다». 오른쪽 위에는 «큰 화면으로 보기» · «폴더 열기» · «지우기» 가 있고, 지우기는 «저장 폴더의 원본 파일도 함께 지워집니다. 되돌릴 수 없습니다» 를 먼저 묻습니다.",
      action: "해 볼 것: 영상 칸의 ★ 를 눌러 대표로 세워 보세요.",
    },
    {
      id: "page-shelf-video-big",
      route: P,
      page: "characters",
      anchor: "shelf-video-big",
      title: "큰 화면 — 보면서 바로 대표로",
      body: "선반 칸은 200px 이라 얼굴도 자막도 안 보입니다. «큰 화면으로 보기» 는 그 영상을 화면 가득 띄워 바로 재생하고, 아래 줄에서 «대표로 정하기» · «대표에서 내리기» 를 눌러 보는 김에 그 자리에서 정할 수 있습니다. «닫기» 나 영상 바깥의 검은 바탕을 누르면 닫히고, 영상 자체를 눌러도 닫히지 않습니다 — 재생 막대를 만지다가 창이 사라지면 안 되니까요.",
      action: "해 볼 것: «닫기» 를 누르거나 영상 바깥의 검은 바탕을 눌러 큰 화면을 닫으세요.",
    },
  ],
};

const PAGE_IMAGE_EDITOR: Tutorial = {
  id: "page-image-editor",
  kind: "page",
  page: "characters",
  // 같은 창이 인물·장소·에셋·컷 어디서나 열립니다(규칙 1) — 목록에도 그렇게 섭니다.
  pages: ["characters", "scenes", "finish"],
  title: "이미지 편집 — 자르기 · 지우기 · 표시 · 동선",
  summary: "그림 한 장에서 쓸 칸만 잘라 내고, 시키지 않은 물건을 지우고, 자리에 번호를 찍고, 동선을 긋고, 파노라마·전개도를 여섯 면으로 나누는 창입니다.",
  steps: [
    {
      id: "page-image-editor-open",
      route: P,
      page: "characters",
      anchor: "card-image-crop",
      title: "가위 — 이 창을 여는 자리",
      body: "그림 위에 마우스를 올리면 나오는 가위가 이 창을 엽니다. 그림을 밖으로 내보내 고치는 곳이 아니라, 한 장에서 «쓸 칸만 잘라 내고 · 시키지 않은 물건을 덮고 · 자리에 번호를 찍고 · 화살표를 긋는» 곳입니다. 나온 파일은 전부 그 항목의 폴더에 새 이름으로 남아, 다음 시트의 레퍼런스나 생성기에 올릴 그림이 됩니다.",
      action: "해 볼 것: 그림에 마우스를 올려 가위를 누르세요.",
      why: "캐릭터에만 있지 않은 까닭 — 자리를 짚고 화살표를 그리는 일은 배경의 성질이 아니라 그림의 성질입니다. 인물·장소·에셋·컷 어디서 눌러도 같은 창입니다(규칙 1).",
    },
    {
      id: "page-image-editor-tabs",
      route: P,
      page: "characters",
      anchor: "cropper-tabs",
      title: "탭 다섯 — 무엇을 하는 창인가",
      body: "«자르기 · 지우기» 는 칸을 잘라 파일로 만들고 시키지 않은 물건을 덮습니다. «표시하기» 는 번호와 도형으로 자리를 짚고, «동선» 은 카메라·인물·빛이 움직이는 길을 화살표로 긋습니다. «파노라마» 는 가로/세로가 1.7 이상인 그림에서만 뜨는 탭으로 360° 한 장을 펴서 여섯 면을 뽑고, «전개도 6면» 은 십자 전개도 한 장을 여섯 칸으로 잘라 저장합니다(이쪽은 넓이와 상관없이 늘 보입니다). 어느 탭이든 «저장» 을 누르기 전에는 파일이 하나도 생기지 않습니다.",
      action: "해 볼 것: 탭을 하나씩 눌러 무엇이 있는지 보세요.",
    },
    {
      id: "page-image-editor-surface",
      route: P,
      page: "characters",
      anchor: "cropper-surface",
      title: "그리기 면 — 자르기냐 지우기냐",
      body: "그림 위를 사각형으로 끌면 상자가 하나 생깁니다. 아래 «자르기»(가위)는 그 상자가 «파일이 될 칸», «지우기»(지우개)는 «둘레 색으로 덮을 자리» 라는 뜻입니다 — 손짓이 같으니 지금 어느 쪽인지 보고 그으세요. 자른 그림은 화면 크기가 아니라 원본 해상도로 저장되고, 지우기가 자르기보다 먼저 적용되어 같은 창에서 지운 자리는 잘라낸 칸에도 반영됩니다. 지우기 상자가 하나라도 있으면 면 오른쪽 위에 «원본»/«미리보기» 토글이 생겨, «미리보기» 로 지운 판을 보면서 상자를 계속 고칠 수 있습니다.",
      action: "해 볼 것: 그림 위를 끌어 상자를 하나 그려 보세요.",
    },
    {
      id: "page-image-editor-undo",
      route: P,
      page: "characters",
      anchor: "cropper-undo",
      title: "되돌리기 · 다시 하기",
      body: "«되돌리기»(Ctrl+Z)는 상자 추가·삭제·덮을 색 바꾸기를 한 칸 되돌리고, «다시 하기»(Ctrl+Shift+Z, Ctrl+Y 도 같습니다)가 되돌린 것을 다시 적용합니다. 되돌릴 것이 없으면 단추가 흐려집니다. 이름 칸에 글자를 치는 동안에는 그 칸의 되돌리기가 먼저라 이 단축키가 물러납니다.",
      action: "해 볼 것: 상자를 하나 그린 뒤 Ctrl+Z 로 되돌려 보세요.",
      why: "이 단축키는 «자르기 · 지우기» 탭에서만 듣습니다. 표시하기 탭에는 그 탭의 되돌리기가 따로 있는데 둘 다 살아 있던 동안에는 Ctrl+Z 한 번에 자르기 상자 하나와 표시 하나가 같이 사라졌습니다.",
    },
    {
      id: "page-image-editor-boxes",
      route: P,
      page: "characters",
      anchor: "cropper-box-list",
      title: "저장될 파일 — 이름과 덮을 색",
      body: "오른쪽에 상자마다 한 줄이 섭니다. 자르기 상자는 «이 칸의 이름» 을 적는 칸이고 그 이름이 곧 파일 이름이자 마그니픽 @태그가 되니, 레퍼런스 구성에 있는 이름을 그대로 쓰면 나중에 찾기 쉽습니다. 지우기 상자는 이름 대신 «덮을 색» 고르개가 있고, 손대지 않으면 상자 둘레 색을 평균 내어 씁니다 — 고른 색을 버리고 그 방식으로 돌아가려면 옆의 «자동». 휴지통(«이 자리 지우기»)은 그 상자 하나만 없애고 Ctrl+Z 로 되살아납니다. 아래 «저장될 파일» 에 무엇이 어떤 이름과 크기로 생길지 미리 보입니다(번호는 저장할 때 붙습니다).",
      action: "해 볼 것: 잘라낼 칸에 이름을 하나 적어 보세요.",
    },
    {
      id: "page-image-editor-upscale",
      route: P,
      page: "characters",
      anchor: "cropper-upscale",
      title: "업스케일 — 엔진과 목표 크기",
      body: "칸을 자르면 그림이 작아지니 키우는 자리가 여기 있습니다. «엔진» 은 설정의 기본 엔진 대신 이 창에서 쓸 것을 따로 고르는 칸이고(설치된 것만 뜨며 실험 엔진에는 « (실험)» 이 붙습니다), «2K» «4K» «6K» «8K» 는 목표로 삼을 긴 변입니다 — 고른 엔진이 진짜로는 못 만드는 크기에 «4K*» 처럼 별표가 붙고 «늘린 그림이 됩니다» 라고 알려 줍니다. «업스케일해서 저장» 을 켜면 저장한 파일을 그 자리에서 키워 같은 이름에 덮어씁니다. 설치된 엔진이 하나도 없으면 설정 → 업스케일 엔진으로 가라는 안내만 나옵니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 이 컴퓨터의 그래픽카드로 몇 분씩 돌고 덮어쓴 것은 되돌릴 수 없습니다.",
    },
    {
      id: "page-image-editor-upscale-now",
      route: P,
      page: "characters",
      anchor: "cropper-upscale-now",
      title: "지금 그림 업스케일 — 새 파일로",
      body: "위의 «업스케일해서 저장» 과 다른 단추입니다. 자르지도 지우지도 않고 지금 보고 있는 그림만 키워 원본 옆에 «…_업스케일_NNN» 을 새로 만듭니다 — 원본은 그대로 남습니다. 폴더에 저장된 그림에서만 눌리고(끌어다 놓기만 한 그림은 «폴더에 저장된 그림만 키울 수 있습니다» 로 막힙니다), 도는 동안에는 저장과 닫기가 함께 잠깁니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 엔진이 몇 분 돌고 취소할 수 없습니다.",
      why: "이름이 갈리는 까닭 — 한쪽은 덮어쓰고 한쪽은 새 파일입니다. 둘이 같은 이름을 쓰면 어느 것이 손대지 않은 원본인지 알 수 없게 됩니다.",
    },
    {
      id: "page-image-editor-footer",
      route: P,
      page: "characters",
      anchor: "cropper-footer",
      title: "아래 띠 — 미리보기 새로 고침 · 저장 · 닫기",
      body: "상자를 그리면 미리보기가 저절로 만들어지지만, 기다리지 않고 지금 보고 싶으면 «미리보기 새로 고침» 을 누릅니다(«잠시 뒤 새로 고침…» «만드는 중…» 으로 바뀌는 동안이 굽는 중입니다). 지우기 상자가 있으면 왼쪽에 «지움 뒤에 붙일 말(선택)» 칸이 생겨, «손» 이라 적으면 지운 판이 «냥이_클로즈업_지움_손_001» 로 남습니다. 오른쪽 «3칸 잘라 · 1곳 지워 저장» 처럼 무엇을 할지가 적힌 단추가 실제로 파일을 만드는 자리이고, «닫기» 는 저장·업스케일이 도는 동안 흐려집니다 — 창 오른쪽 위 ×, ESC, 바깥 클릭도 같은 길이라 도는 중에는 «저장·업스케일이 도는 중입니다» 알림만 뜹니다.",
      action: "해 볼 것: «미리보기 새로 고침» 을 눌러 결과를 먼저 보세요 — «저장» 을 누르기 전에는 파일이 생기지 않습니다.",
      why: "도는 중에 닫히면 부모가 이 창을 없애 진행 표시가 통째로 사라지고, 몇 분 걸리는 일이 화면 밖에서 돕니다. 그 사이 다른 창에서 업스케일을 또 걸면 엔진 둘이 겹칩니다.",
    },
    {
      id: "page-image-editor-mark",
      route: P,
      page: "characters",
      anchor: "cropper-mark-shapes",
      title: "표시하기 — 앵커 · 사각형 · 원 · 자유선",
      body: "그림 위의 자리를 짚어 «①번 지점» 이라 부를 수 있게 만드는 탭입니다. 네 단추로 모양을 고르고 그림 위를 끌면 표시가 하나 더해지는데, «앵커 지점» 만 성격이 달라 카메라가 설 점을 누르고 정면으로 볼 쪽으로 끌어 놓습니다(클릭 한 번으로도 찍힙니다). 표시마다 아래에 설명 칸이 서고 모양에 따라 안내가 달라집니다 — 앵커는 «이 지점이 어디인지», 자유선은 «동선이나 흐름», 사각형·원은 «이 구역이 무엇인지». 휴지통(«이 표시 지우기»)은 그 표시 하나를, «마지막 표시 취소» 와 Ctrl+Z 는 가장 나중에 찍은 것 하나를 지웁니다. 단추줄 끝의 «움직임 구역» 은 모양이 아니라 **스위치**라, 켜 둔 동안 그린 사각형·원·자유선은 표시가 아니라 «여기는 움직여도 된다» 는 뜻이 됩니다(앵커 지점에는 안 켜집니다 — 점이라 칠할 넓이가 없어서요).",
      action: "해 볼 것: 모양을 하나 고르고 그림 위를 끌어 표시해 보세요.",
    },
    {
      id: "page-image-editor-mark-save",
      route: P,
      page: "characters",
      anchor: "cropper-mark-shapes",
      title: "표시한 그림 저장 · 복사",
      body: "표시를 하나라도 찍으면 이름 칸과 단추가 생깁니다. 이름 칸(기본값 «표시»)은 저장될 파일 이름에 들어갈 말이라 «앵커 A» 라 적으면 «원본 이름_표시_앵커 A» 로 남습니다. «표시한 그림 저장» 은 번호·도형을 원본 해상도로 구운 PNG 를 이 항목 폴더에 새 파일로 두고 생성 이미지 목록에도 넣어, 원본은 깨끗한 채로 «앵커 A판» «앵커 B판» 이 쌓이게 합니다. 파일을 남기지 않고 프리픽·claude.ai 에 바로 붙여넣을 거면 «표시한 그림 복사» 로 클립보드에 담으세요 — 번호가 보여야 생성기가 «①번 지점» 을 알아봅니다. «움직임 구역» 을 켜고 그린 자리는 «움직임 마스크 저장» 으로 그 자리만 하얀 흑백 PNG(«원본 이름_움직임»)가 되고, 흰 구역만 움직이고 나머지는 첫 프레임 그대로 붙박입니다 — 달리는 차 안의 창밖처럼 배경이 통째로 얼어붙는 컷에 씁니다. 로컬 영상은 그린 뒤 자동으로 물립니다.",
      action: "해 볼 것: 이름 칸에 «앵커 A» 처럼 적어 보세요.",
    },
    {
      id: "page-image-editor-motion",
      route: P,
      page: "characters",
      anchor: "cropper-motion",
      title: "동선 — 카메라 · 인물 · 빛이 움직이는 길",
      body: "그림 위에 화살표 달린 선을 그어 영상 생성기에 «무엇이 어디로 움직이는지» 를 못 박는 탭입니다. 왼쪽에서 «카메라 동선»(보라 점선) · «인물 동선»(파랑 실선) · «빛 동선»(가는 3중선) 중 갈래를 고르고, 옆 세 단추로 «구경만 하기»(실수로 선이 그어지지 않게) · «자유선»(끄는 자리를 그대로) · «직선»(시작점과 끝점만)을 고릅니다. «굵기»(0.3~2)는 앞으로 그릴 선에만 걸리니 긋기 전에 정하세요 — 이미 그은 선은 안 바뀝니다. 되돌리기 단추(«마지막 선 하나만 지웁니다»)와 Ctrl+Z 는 방금 그은 선 하나를 지우고, «동선 그림 저장» 은 선을 원본 해상도에 구워 «원본 이름_동선» 으로 이 항목 폴더에 남깁니다.",
      action: "해 볼 것: 갈래와 도구를 고르고 그림 위를 끌어 선을 하나 그어 보세요.",
    },
    {
      id: "page-image-editor-pano",
      route: P,
      page: "planner",
      anchor: "cropper-pano-howto",
      title: "파노라마 탭 — 먼저 «사용 방법 보기»",
      body: "가로/세로가 1.7 이상인 그림에서만 뜨는 탭입니다. 360° 로 뽑은 한 장을 등장방형(2:1)으로 펴 놓고 거기서 정면·후면·좌·우·위·아래 여섯 장을 잘라 내는 곳이고, 구도잡기의 방과 돔이 그 여섯 면을 그대로 씁니다. 오른쪽 «사용 방법 보기» 를 누르면 6면 배경을 만드는 다섯 걸음(어떤 칩으로 뽑고 · 무엇을 레퍼런스로 넣고 · 어디에 거는지)이 펼쳐지고 «접기» 로 접힙니다 — 열고 닫은 상태는 이 컴퓨터에만 기억됩니다.",
      action: "해 볼 것: «사용 방법 보기» 를 눌러 다섯 걸음을 읽어 보세요.",
    },
    {
      id: "page-image-editor-pano-fix",
      route: P,
      page: "planner",
      anchor: "cropper-pano-fix",
      title: "펴기 — 세로 화각 · 지평선 · 이음매",
      body: "여기 손잡이들은 그림을 꾸미는 칸이 아니라 «원본이 무엇을 담고 있는지» 를 알려 주는 칸입니다. «이미 등장방형 파노라마 (세로 180도 — 손대지 않음)» 는 기본으로 켜져 있고, 켜 둔 동안에는 «세로 화각» 과 «지평선 위치» 가 잠깁니다. 4:1 처럼 납작하거나 위아래 왜곡이 없는 그림이면 «세로 모형» 을 «원통» 으로 바꾸세요(잠금이 풀리며 비율에서 화각을 어림잡아 넣습니다). 21:9 등장방형처럼 «등장방형인데 180도가 아닌» 것은 «등장방형» 을 눌러 잠금만 풀고 «세로 화각» 을 154 쯤으로 내립니다 — 그 값을 만들 수 있는 유일한 길입니다. «지평선 위치» 는 원본에서 수평선이 있는 높이(어긋나면 여섯 면이 전부 기울어집니다), «이음매 잇기» 는 왼쪽 끝과 오른쪽 끝을 섞어 한 바퀴 자국을 지우는 폭, «하늘·바닥 채우기»(실내 배경이면 «천장·바닥 채우기»)는 원본에 없는 위아래 극점을 가장자리 색으로 늘여 덮습니다.",
      action: "해 볼 것: «지평선 위치» 를 끌어 점선이 수평선에 닿게 맞춰 보세요.",
      why: "위 면과 바닥 두 장만 보면 맞았는지 압니다 — 하늘이 위쪽 면에 안 담기고 옆면 위로 밀려 있으면 세로 화각이 너무 작은 것이고, 위쪽 면이 밋밋한 색 뚜껑만 되면 너무 큰 것입니다.",
    },
    {
      id: "page-image-editor-pano-faces",
      route: P,
      page: "planner",
      anchor: "cropper-pano-faces",
      title: "여섯 면 만들기 · 보정한 파노라마 저장",
      body: "«보정한 파노라마 저장» 은 지금 손잡이대로 편 등장방형 한 장을 «…_파노라마» 이름으로 «파노라마» 폴더에 따로 두고, «여섯 면 만들기» 는 거기서 여섯 장을 잘라 «6면» 폴더에 한 세트로 저장해 구도잡기 환경 탭의 «6면 세트» 에 바로 걸리게 합니다. 위의 «여섯 면 크기» 가 한 면의 한 변(1024 · 2048 · 4K · 6K · 8K)이고, 그 아래 줄이 «이 파노라마의 한 면 원래 해상도» 와 견줘 «늘리는 것뿐» 인지 «엔진으로 업스케일» 인지 알려 줍니다. 엔진이 깔려 있으면 «작으면 업스케일 (엔진 이름)» 체크가 생기고, 켜면 면마다 진짜로 키우며 «정면 업스케일 중 1/6» 처럼 진행이 보입니다.",
      action: "해 볼 것: 자리만 확인하세요. 누르면 여섯 장을 굽고, 업스케일을 켜 두었으면 몇 분 돌며 그동안 창을 닫을 수 없습니다.",
    },
    {
      id: "page-image-editor-cross",
      route: P,
      page: "planner",
      anchor: "cropper-cross-lines",
      title: "전개도 6면 — 자르는 선 맞추기",
      body: "십자 전개도 한 장을 여섯 칸으로 직접 자르는 탭입니다. 층고가 낮은 실내 십자는 16:9 언저리라 파노라마 탭에 안 걸리므로 이 탭은 넓이와 상관없이 늘 보입니다. 열면 회색 바탕을 재서 경계를 자동으로 잡고, 어긋나면 보라 세로선 셋·하늘색 가로선 넷을 끌어 맞춥니다 — 이웃 선은 넘지 못하고, 끄는 동안 돋보기가 그 자리를 따라옵니다. 선을 한 번 눌러 고르면(노랑) 방향키로 원본 1 px, Shift 와 함께면 10 px 씩 옮길 수 있습니다 — 화면 픽셀로는 못 집는 한 줄을 그렇게 맞춥니다.",
      action: "해 볼 것: 선을 하나 눌러 고른 뒤 방향키로 1 px 씩 옮겨 보세요.",
      why: "잡는 띠는 10 px 이고 그 한가운데가 실제 자르는 자리입니다. 예전에는 가로선이 5 px 위에 그려져 돋보기와 전체 화면이 달라 보였습니다 — 자르는 값은 처음부터 맞았고 그리기만 틀렸습니다.",
    },
    {
      id: "page-image-editor-cross-save",
      route: P,
      page: "planner",
      anchor: "cropper-cross-tools",
      title: "확대 · 돋보기 · 여섯 면으로 저장",
      body: "«축소» · «확대» 와 돋보기로 자르는 선을 확인하고 «자리 다시 찾기» 로 자동 감지를 다시 합니다. «천장·바닥 뒤집기» 는 원본 방향에 맞춥니다. «면 비율과 경계를 확인한 뒤 저장해 주세요» 가 뜨면 표시된 면과 방 치수·회색 여백을 비교하세요. 의심되는 면이 있으면 저장이 막히며, 선을 고치거나 빠진 면을 포함해 다시 생성해야 합니다. «여섯 면으로 저장» 은 확인한 여섯 칸을 «6면» 폴더에 저장합니다.",
      action: "해 볼 것: «확대» 로 키워 선이 맞는지 보세요. «여섯 면으로 저장» 은 자리만 확인하세요 — 누르면 여섯 장이 폴더에 한 세트로 생깁니다.",
    },
  ],
};

export const PAGE_TUTORIALS: Tutorial[] = [PROJECTS, BASICS, CHARACTERS, SCENES, FINISH, SETTINGS, BGM,
  PAGE_LINEAGE,
  PAGE_SHEET,
  PAGE_SHELF,
  PAGE_IMAGE_EDITOR,
];
