import { useEffect, useState, useRef } from "react";
import { toast } from "sonner";
import { useT } from "@/lib/i18n";
import { chooseComfyWorkflowFile } from "@/lib/upscale";
import { getComfyGenerationSettings, saveComfyGenerationSettingsAndConfirm } from "@/lib/comfyGeneration";
import { inspectAndRegisterWorkflow, listWorkflowLibrary, subscribeWorkflowLibrary,recordMusic3UserAuthorization,readWorkflowPreflight } from "@/lib/comfyWorkflowLibrary";
import { invoke } from "@tauri-apps/api/core";
import { listLocalProjects } from "@/lib/localProjectStore";
import { loadBgmProjects } from "@/lib/bgmProjects";
import music3Candidate from "@/lib/workflowEvidence/music3-instrumental-smoke.candidate.json";
import type { WorkflowGraph } from "@/lib/comfyWorkflowContract";
import WorkflowRoleEditor from "./WorkflowRoleEditor";
import {newWorkflowEditorDraft,readEditableApiGraph,normalizeWorkflowEditorDraft,type WorkflowEditorDraft} from "@/lib/workflowEditor";
import {offlineWorkflowCandidates,offlineWorkflowDraft,offlineWorkflowBlockerLabel,OFFLINE_CATALOG_CAPTURED_AT} from "@/lib/offlineWorkflowCatalog";
import {hasOfflineWorkflowV2Draft,offlineWorkflowV2Draft} from "@/lib/offlineWorkflowV2Draft";
import {chooseWorkflowRegistrationFile,readWorkflowIndexRegistration,type WorkflowIndexEntry} from "@/lib/workflowFileImport";

export default function WorkflowLibraryPanel(){
 const t=useT(),[entries,setEntries]=useState(listWorkflowLibrary),[settings,setSettings]=useState(getComfyGenerationSettings),[path,setPath]=useState(""),[contract,setContract]=useState(""),[busy,setBusy]=useState(false);
 const [authorizationOptions,setAuthorizationOptions]=useState<Awaited<ReturnType<typeof import("../lib/workflowProjectAuthorization").readWorkflowAuthorizationOptions>>>(),[authorizationPreset,setAuthorizationPreset]=useState(""),[authorizationEvidence,setAuthorizationEvidence]=useState("");
 const [projectId,setProjectId]=useState(""),[owned,setOwned]=useState<{installationRoot:string;sharedModels:string;port:number;idleEndpoints:string[];presetIds:string[]}>({installationRoot:"",sharedModels:"",port:8190,idleEndpoints:[],presetIds:[]}),[backend,setBackend]=useState<{state:string;baseUrl?:string;record?:{baseUrl:string};logPath?:string}>();
 const [graph,setGraph]=useState<WorkflowGraph>(),[graphPath,setGraphPath]=useState(""),pathRef=useRef(path),undo=useRef<string[]>([]),redo=useRef<string[]>([]);
 const [index,setIndex]=useState<{root:string;entries:WorkflowIndexEntry[]}>(),[importHash,setImportHash]=useState<string>(),contractRef=useRef(contract);
 const [nativeContracts,setNativeContracts]=useState<{supportedWorkflowContractVersions:number[];executablePresets:{id:string;modelRuleId:string;contractVersions:number[]}[];registryError?:string}>();
 pathRef.current=path;
 contractRef.current=contract;
 let editor:WorkflowEditorDraft|undefined;
 try{const raw=JSON.parse(contract);if(raw.source&&Array.isArray(raw.selection?.slots)&&Array.isArray(raw.selection?.promptRoles))editor={...raw,selection:{...raw.selection,referenceGroups:raw.selection.referenceGroups??[]}};}catch{/* 입력 중인 JSON을 그대로 보존합니다. */}
 const edit=(next:WorkflowEditorDraft)=>{undo.current=[...undo.current.slice(-49),contract];redo.current=[];setContract(JSON.stringify(next,null,2));};
 const loadEditor=async()=>{const requestedPath=path,requestedContract=contract;setBusy(true);try{if(contract&&!editor)throw new Error("workflow_contract_invalid: 편집 중인 계약 JSON을 먼저 완성하세요.");if(editor&&editor.source.workflowPath!==requestedPath)throw new Error("workflow_path_changed: 기존 계약의 파일과 다릅니다. 기존 계약을 보존한 뒤 새 초안을 선택하세요.");const facts=await readWorkflowPreflight(requestedPath);if(pathRef.current!==requestedPath||contractRef.current!==requestedContract)throw new Error("workflow_path_or_editor_changed: 읽는 동안 파일·편집안이 바뀌어 응답을 적용하지 않습니다.");if(importHash&&facts.sha256!==importHash)throw new Error("workflow_import_graph_hash_changed");setGraph(readEditableApiGraph(facts.text));setGraphPath(requestedPath);if(!editor){edit(newWorkflowEditorDraft(facts.text,requestedPath));}redo.current=[];}catch(error){toast.error(String(error));}finally{setBusy(false);}};
 const applyImport=(draft:WorkflowEditorDraft,expected?:string)=>{edit(draft);setPath(draft.source.workflowPath);setGraph(undefined);setGraphPath("");setImportHash(expected);};
 const pickRegistration=async()=>{const requestedContract=contract,requestedPath=path;setBusy(true);try{const result=await chooseWorkflowRegistrationFile(index?.root??"");if(!result)return;if(contractRef.current!==requestedContract||pathRef.current!==requestedPath)throw new Error("workflow_editor_changed: 파일 선택 중 수정한 내용을 보존했습니다. 다시 가져오세요.");if(result.kind==="index")setIndex({root:result.root,entries:result.entries});else applyImport(result.draft);}catch(error){toast.error(String(error));}finally{setBusy(false);}};
 const pickIndexEntry=async(entry:WorkflowIndexEntry,version:"v1"|"v2")=>{if(!index)return;const requestedContract=contract,requestedPath=path;setBusy(true);try{const result=await readWorkflowIndexRegistration(index.root,entry,version);if(contractRef.current!==requestedContract||pathRef.current!==requestedPath)throw new Error("workflow_editor_changed");applyImport(result.draft,result.expectedGraphSha256);}catch(error){toast.error(String(error));}finally{setBusy(false);}};
 useEffect(()=>{void invoke<typeof owned>("comfy_owned_backend_defaults").then(value=>setOwned({...value,installationRoot:value.installationRoot??"",sharedModels:value.sharedModels??""})).catch(()=>undefined);},[]);
 useEffect(()=>{void import("../lib/workflowProjectAuthorization").then(module=>module.readWorkflowAuthorizationOptions()).then(setAuthorizationOptions).catch(error=>toast.error(String(error)));},[]);
 useEffect(()=>{void invoke<NonNullable<typeof nativeContracts>>("comfy_workflow_contract_capabilities").then(setNativeContracts).catch(()=>undefined);},[]);
 const projects=[...listLocalProjects().map(project=>({id:project.id,label:project.title})),...loadBgmProjects().map(project=>({id:project.id,label:`BGM · ${project.name}`}))];
 useEffect(()=>subscribeWorkflowLibrary(()=>setEntries(listWorkflowLibrary())),[]);
 const inspect=async()=>{setBusy(true);try{const raw=normalizeWorkflowEditorDraft(JSON.parse(contract) as WorkflowEditorDraft);if(raw.source.workflowPath!==path)throw new Error("workflow_path_changed: 계약의 원본 파일과 선택 경로가 다릅니다.");const expectedGraphSha=importHash??offlineWorkflowCandidates.find(candidate=>candidate.id===raw.source.presetId)?.graphSha256;if(expectedGraphSha&&(await readWorkflowPreflight(path)).sha256!==expectedGraphSha)throw new Error("workflow_offline_graph_mismatch: 후보의 정확한 API graph와 선택 파일의 SHA가 다릅니다. 다른 파일에 역할을 자동 적용하지 않습니다.");
  const result=await inspectAndRegisterWorkflow({...raw,projectId:projectId||undefined,source:{...raw.source,workflowPath:path}});
  toast.message(result.manifest?t("정적·설치 조건 검사를 통과했습니다. 실제 생성·등록은 미검증입니다."):t("초안을 보관했습니다. 검사 차단 사유를 확인하세요."));}catch(error){toast.error(String(error));}finally{setBusy(false);}};
 return <div className="space-y-3 text-xs">
  <p className="text-amber-200">{t("기존 라이브러리에서 역할을 선택하거나 새 API JSON·등록 entry 파일을 가져올 수 있습니다. 가져오기는 생성 허가와 별개이며 이전 버전과 원본 파일을 보존합니다. 실제 생성·수집·등록 검증은 아직 없습니다.")}</p>
  <button disabled={busy} onClick={()=>void pickRegistration()}>{t("등록 entry / INDEX.json 파일 가져오기")}</button>
  {nativeContracts&&<p>{t("계약 기능 지원")}: {nativeContracts.supportedWorkflowContractVersions.map(version=>`V${version}`).join(", ")} · {t("등록된 실행 preset")}: {nativeContracts.executablePresets.map(preset=>`${preset.modelRuleId} (${preset.contractVersions.map(version=>`V${version}`).join(", ")})`).join(", ")||t("없음")} · {t("각 요청의 현재 환경·허가 증거는 실행 직전에 별도로 검사합니다.")}</p>}
  {nativeContracts?.registryError&&<p className="text-amber-200">{t("패키지 실행 registry 검사 실패")}: {nativeContracts.registryError}</p>}
  {index&&<details open className="rounded border border-white/10 p-2"><summary>{t("직접 선택한 workflow 폴더의 목록")}: {index.root}</summary><p>{t("목록의 파일만 읽습니다. 설치·허가·생성 표시를 신뢰하지 않고 가져온 뒤 다시 검사합니다.")}</p>{index.entries.map(entry=><div key={entry.id} className="my-1">{entry.model} · {entry.operation} · {entry.referenceCount} {t("참조")} · {entry.id}{(["v1","v2"] as const).filter(version=>entry.versions[version]).map(version=><button key={version} disabled={busy} onClick={()=>void pickIndexEntry(entry,version)}>{version} {t("등록 초안 가져오기")}</button>)}</div>)}</details>}
  <div className="flex gap-2"><input aria-label={t("Comfy 서버 주소")} className="grow rounded bg-black/20 p-2" value={settings.baseUrl} onChange={event=>setSettings({...settings,baseUrl:event.target.value})}/>
   <button onClick={()=>void saveComfyGenerationSettingsAndConfirm(current=>({...current,baseUrl:settings.baseUrl,installationRoot:settings.installationRoot})).then(()=>toast.success(t("이전 주소와 mapping을 보관하고 연결을 저장했습니다."))).catch(error=>toast.error(String(error)))}>{t("연결 저장")}</button></div>
  <input aria-label={t("검사한 Comfy 설치 폴더")} value={settings.installationRoot??""} onChange={event=>setSettings({...settings,installationRoot:event.target.value})} placeholder={t("기존 Comfy 설치 폴더 (소스 hash/commit 읽기 검사)")} className="w-full rounded bg-black/20 p-2"/>
  <p className="text-white/60">{t("2026-10-06 Desktop 로그·읽기 검사에서 8189/core0.39가 확인됐습니다. 8188/core0.36은 별도 서버입니다. 기존 주소는 보존했으며 연결 저장 전에 사용할 인스턴스를 선택하세요. 설치 노드 수는 코드 검토나 생성 성공의 증거가 아닙니다.")}</p>
  <button onClick={()=>setSettings(current=>({...current,baseUrl:"http://127.0.0.1:8189"}))}>{t("Desktop 확인 주소를 편집 칸에 넣기")}</button>
  <details className="rounded border border-white/10 p-2"><summary>{t("앱 소유 검증 backend")}</summary>
   <p className="my-2 text-white/60">{t("기존 Desktop 서버를 유지합니다. 검토된 소스의 별도 복사본·기존 venv·Shared 파일로 loopback child를 시작합니다. 유휴 큐·메모리를 검사하고 custom/API/다운로드를 차단합니다. 연결 주소는 따로 저장해야 적용됩니다.")}</p>
   <input aria-label={t("앱 소유 source 원본 폴더")} value={owned.installationRoot} onChange={event=>setOwned({...owned,installationRoot:event.target.value})} className="w-full rounded bg-black/20 p-2"/>
   <input aria-label={t("기존 Shared models 폴더")} value={owned.sharedModels} onChange={event=>setOwned({...owned,sharedModels:event.target.value})} className="w-full rounded bg-black/20 p-2"/>
   <label>{t("loopback 포트")}<input type="number" value={owned.port} onChange={event=>setOwned({...owned,port:Number(event.target.value)})}/></label>
   {nativeContracts?.executablePresets.map(preset=><label key={preset.id} className="block"><input type="checkbox" checked={owned.presetIds.includes(preset.id)} onChange={event=>setOwned(current=>({...current,presetIds:event.target.checked?[...current.presetIds,preset.id]:current.presetIds.filter(id=>id!==preset.id)}))}/>{preset.modelRuleId} · {preset.id}</label>)}
   <button disabled={busy||!owned.presetIds.length} onClick={()=>{setBusy(true);void invoke<{state:string;baseUrl:string;logPath:string}>("comfy_owned_backend_start",{request:owned}).then(setBackend).catch(error=>toast.error(String(error))).finally(()=>setBusy(false));}}>{t("앱 소유 backend 시작·재사용")}</button>
   <button onClick={()=>void invoke<typeof backend>("comfy_owned_backend_status").then(setBackend).catch(error=>toast.error(String(error)))}>{t("시작 상태·소스 증명 확인")}</button>
   <button onClick={()=>void invoke("comfy_owned_backend_stop").then(()=>toast.message(t("앱 소유 child의 정상 종료를 요청했습니다."))).catch(error=>toast.error(String(error)))}>{t("앱 소유 child 정상 종료")}</button>
   {backend&&<p>{backend.state} · {backend.baseUrl??backend.record?.baseUrl} · {backend.logPath}</p>}
   {backend?.state==="ready"&&<button onClick={()=>setSettings(current=>({...current,baseUrl:backend.record!.baseUrl}))}>{t("검증 backend 주소를 편집 칸에 넣기")}</button>}
  </details>
  <label>{t("검사·허가 대상 프로젝트")}<select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">{t("프로젝트 선택")}</option>{projects.map(project=><option key={project.id} value={project.id}>{project.label}</option>)}</select></label>
  {editor&&<button disabled={busy||!projectId} onClick={()=>applyImport({...editor,source:{...editor.source,workflowId:`workflow-${crypto.randomUUID()}`}},importHash)}>{t("이 프로젝트용 새 ID로 복사 (역할·원문 보존)")}</button>}
  <details className="rounded border border-white/10 p-2"><summary>{t("정확한 프로젝트·파일 범위의 사용자 허가 진술 기록")}</summary><p>{t("보유한 허가의 출처와 내용을 직접 기록합니다. 공개 라이선스 검증이나 권한 부여가 아니며 가져온 workflow의 허가 표시는 채택하지 않습니다.")}</p><select aria-label={t("허가 진술 대상 검토 preset")} value={authorizationPreset} onChange={event=>setAuthorizationPreset(event.target.value)}><option value="">{t("검토된 preset 선택")}</option>{authorizationOptions?.presets.map(preset=><option key={preset.id} value={preset.id}>{preset.modelRuleId} · {preset.id}</option>)}</select>{authorizationOptions?.presets.find(preset=>preset.id===authorizationPreset)?.files.map(file=><p key={file.category+file.name} className="break-all">{file.category}/{file.name} · {file.sha256}</p>)}<textarea aria-label={t("사용자 허가 진술·출처")} value={authorizationEvidence} onChange={event=>setAuthorizationEvidence(event.target.value)} placeholder={t("사용자가 진술한 허가 내용과 근거·출처를 입력하세요.")}/><button disabled={busy||!projectId||!authorizationEvidence.trim()||!authorizationPreset} onClick={()=>{const preset=authorizationOptions?.presets.find(preset=>preset.id===authorizationPreset);if(!preset)return;setBusy(true);void import("../lib/comfyWorkflowLibrary").then(module=>module.recordWorkflowUserAuthorization({projectId,presetId:preset.id,modelRuleId:preset.modelRuleId,registrySha256:authorizationOptions!.registrySha256,files:preset.files,statement:{kind:"user-reported",evidence:authorizationEvidence,sourceThreadId:"local-user-record",reportedAtUtc:new Date().toISOString()}})).then(()=>toast.success(t("선택 프로젝트와 정확 파일 범위에 사용자 진술을 저장했습니다."))).catch(error=>toast.error(String(error))).finally(()=>setBusy(false));}}>{t("명시한 사용자 진술 저장")}</button></details>
  <button disabled={!projectId||busy} onClick={()=>void recordMusic3UserAuthorization(projectId).then(()=>toast.success(t("이미 진술한 Music3 허가를 이 프로젝트의 정확 3개 파일 SHA에 기록했습니다. 독립 법률 검증은 아닙니다."))).catch(error=>toast.error(String(error)))}>{t("이 프로젝트의 기존 Music3 허가 기록 적용")}</button>
  <button disabled={!projectId||busy} onClick={()=>void invoke<{workflowPath:string}>("comfy_owned_music3_candidate").then(value=>{setGraph(undefined);setPath(value.workflowPath);setContract(JSON.stringify({source:{...music3Candidate.source,workflowId:`music3-smoke-${projectId}`,workflowPath:value.workflowPath},selection:music3Candidate.selection},null,2));}).catch(error=>toast.error(String(error)))}>{t("Music3 최소 초안 불러오기 (생성 미검증)")}</button>
  <details className="rounded border border-amber-300/20 p-2"><summary>{t("오프라인 모델 후보 27개 · 실행 차단")}</summary>
   <p>{t("소스·역할 초안을 보는 후보 목록입니다. 실행 allowlist와 허가 기록을 채택하지 않습니다. API 파일을 고른 뒤 그 파일의 SHA와 현재 환경을 별도로 검사합니다.")} {OFFLINE_CATALOG_CAPTURED_AT}</p>
   {offlineWorkflowCandidates.map(candidate=><details key={candidate.id} className="my-2 rounded bg-black/10 p-2"><summary>{candidate.id} · {candidate.operation} · {candidate.referenceCount} {t("참조")} · {t("미검증 / 실행 차단")}</summary>
    <p className="break-all">{candidate.graphSha256}</p>{candidate.blockers.map(code=><p key={code} className="text-amber-200">{t(offlineWorkflowBlockerLabel(code))}</p>)}
    <p>{candidate.selection.promptRoles.map(role=>role.id+" / "+role.modelRuleId+" / "+role.loaderNodeIds.join(", ")).join(" · ")}</p>
    {candidate.selection.referenceGroups.map(group=><p key={group.id}>{group.id}: {group.role} · {group.minItems}–{group.maxItems} · {group.slotIds.join(" → ")}</p>)}
    <button disabled={busy||!path} onClick={()=>{const result=offlineWorkflowDraft(candidate.id,path,projectId||undefined);edit(result.draft);setGraph(result.graph);setGraphPath(path);}}>{t("선택 API 파일의 역할 초안 보기 (실행 없음)")}</button>
    {hasOfflineWorkflowV2Draft(candidate.id)&&<button disabled={busy||!path} onClick={()=>{const result=offlineWorkflowV2Draft(candidate.id,path,projectId||undefined);edit(result.draft);setGraph(result.graph);setGraphPath(path);}}>{t("V1 원문을 보존한 V2 계약 초안 보기 (실행 증거 별도 검사)")}</button>}
   </details>)}
  </details>
  <div className="flex gap-2"><input aria-label={t("보존할 workflow JSON 경로")} value={path} onChange={event=>setPath(event.target.value)} className="grow rounded bg-black/20 p-2"/><button disabled={busy} onClick={()=>void chooseComfyWorkflowFile().then(value=>{if(value){setPath(value);setImportHash(undefined);}})}>{t("API JSON 고르기")}</button></div>
  <button disabled={busy||!path} onClick={()=>void loadEditor()}>{t("API graph 읽기 · 역할 편집 열기 (생성 없음)")}</button>
  {contract&&editor?.source.workflowPath!==path&&<button disabled={busy||!path} onClick={()=>{undo.current.push(contract);redo.current=[];setContract("");setGraph(undefined);setGraphPath("");}}>{t("이 파일의 새 역할 초안 시작 (기존 계약은 Ctrl+Z로 복구)")}</button>}
  {graph&&graphPath===path&&editor&&editor.source.workflowPath===path&&<div onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){const from=event.shiftKey?redo:undo,to=event.shiftKey?undo:redo;const previous=from.current.pop();if(previous!==undefined){event.preventDefault();to.current.push(contract);setContract(previous);}}}}><WorkflowRoleEditor draft={editor} graph={graph} onChange={edit}/></div>}
  <p className="text-white/60">{t("LLM/Comfy MCP가 만든 graph도 동일하게 초안으로 검사합니다. source/selection 계약에 작업·모델·출처, positive/negative 역할과 실제 loader, 역할별 참조 min/max/순서/identity 및 결과 노드를 명시하세요. fixed 0/1/2/N 변형은 각각 등록합니다. 지원하지 않는 목록 입력은 차단합니다.")}</p>
  <textarea aria-label={t("workflow 역할 계약 JSON")} value={contract} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){const from=event.shiftKey?redo:undo,to=event.shiftKey?undo:redo;const previous=from.current.pop();if(previous!==undefined){event.preventDefault();to.current.push(contract);setContract(previous);}}}} onChange={event=>{undo.current=[...undo.current.slice(-49),contract];redo.current=[];setContract(event.target.value);}} rows={8} placeholder={'{"source":{...},"selection":{"slots":[],"promptRoles":[],"selectedPromptRoleId":"...","outputNodeIds":[],"referenceGroups":[]}}'} className="w-full rounded bg-black/20 p-2 font-mono"/>
  <button disabled={busy||!path||!contract} onClick={()=>void inspect()} className="rounded bg-emerald-500/15 p-2 disabled:opacity-40">{t(busy?"읽기 검사 중":"초안 검사·라이브러리 등록")}</button>
  {entries.map(entry=><details key={entry.source.workflowId} className="rounded border border-white/10 p-2"><summary>{entry.source.title} · {entry.source.operation} · {entry.source.modelIds.join(", ")} · {t(entry.manifest?"정적·설치 검사 통과 / 생성 미검증":"초안 / 실행 차단")}</summary>
   <button disabled={busy} onClick={()=>{applyImport({source:entry.source,selection:entry.selection,selectionEnvelope:entry.selectionEnvelope,voiceOptionBindings:entry.voiceOptionBindings},entry.workflowSha256);if(entry.projectScope??entry.manifest?.projectId)setProjectId((entry.projectScope??entry.manifest?.projectId)!);}}>{t("이 workflow 역할 편집 · 새 버전으로 검사")}</button>
   {entry.originalWorkflowPath&&<button disabled={busy} onClick={()=>applyImport({source:{...entry.source,workflowId:entry.originWorkflowId??entry.source.workflowId,workflowPath:entry.originalWorkflowPath!},selection:entry.selection,selectionEnvelope:entry.selectionEnvelope,voiceOptionBindings:entry.voiceOptionBindings})}>{t("원본 파일 다시 불러오기 준비 (이전 버전 보존)")}</button>}
   <p>{t("보존 버전")}: {entry.revisionId??entry.checkedAtUtc} · {entry.workflowSha256?.slice(0,12)} · {entry.projectScope??entry.manifest?.projectId??t("프로젝트 미지정")}</p>
   {entry.selectionEnvelope&&<p className="text-amber-200">{t("V2 계약 원문을 보존했습니다. 계약 기능은 V1·V2를 지원하며 실제 생성은 등록된 실행 preset과 현재 환경 증거를 별도로 검사합니다.")}</p>}
   <p className="break-all">{entry.manifest?.workflowSha256??entry.source.workflowPath}</p><p>{entry.checkedAtUtc}</p>
   {entry.selection.referenceGroups.map(group=><p key={group.id}>{group.role}: {group.minItems}–{group.maxItems} {group.mediaKind} · {group.strategy} · {group.identity} · {group.slotIds.join(" → ")}</p>)}
   {entry.issues.map((issue,index)=><p className="text-amber-200" key={index}>{issue.code}: {issue.message}</p>)}</details>)}
 </div>;
}
