use super::*;
struct Fixture {root:tempfile::TempDir,policy:LocalPolicy,bytes:Vec<u8>,envelope:Value}
fn fixture(class:&str)->Fixture {
    let root=tempfile::tempdir().unwrap();let mut bundles=vec![];
    let roles=if class=="SDNQSampler"{vec![("diffusers-model","cpu-diffusers")]}else{vec![("tts-model",match class{"FB_Qwen3TTSCustomVoice"=>"Qwen3-TTS-12Hz-1.7B-CustomVoice","FB_Qwen3TTSVoiceDesign"=>"Qwen3-TTS-12Hz-1.7B-VoiceDesign",_=>"Qwen3-TTS-12Hz-1.7B-Base"}),("tts-tokenizer","Qwen3-TTS-Tokenizer-12Hz")]};
    for (role,name) in roles{let dir=root.path().join(name);fs::create_dir(&dir).unwrap();let mut files=vec![];for name in ["config.json","model.safetensors"]{let bytes=b"CPU synthetic bytes; not a model";fs::write(dir.join(name),bytes).unwrap();files.push(BundleFile{relative_path:name.into(),sha256:sha(bytes),bytes:bytes.len() as u64});}let tree=sha(&serde_json::to_vec(&files).unwrap());bundles.push(Bundle{registered_bundle_id:role.into(),role:role.into(),exact_real_path:dir.to_string_lossy().into(),tree_sha256:tree,files});}
    let mut inputs=json!({"text":"CPU only","model_choice":"1.7B"});
    if class=="SDNQSampler"{inputs=json!({"prompt":"CPU only","model_selection":"[Custom Path]","custom_model_path":bundles[0].exact_real_path,"auto_download":false,"num_frames":1,"use_quantized_matmul":false,"use_xformers":false});for i in 1..=5{let prefix=if i==1{"lora".into()}else{format!("lora{i}")};inputs[format!("{prefix}_selection")]=json!("[None]");inputs[format!("{prefix}_custom_path")]=json!("");inputs[format!("{prefix}_strength")]=json!(0);}}
    let graph=json!({"1":{"class_type":class,"inputs":inputs}});let bytes=serde_json::to_vec(&graph).unwrap();
    let base=json!({"promptRoles":[{"id":"primary","modelRuleId":"cpu-local-only"}],"selectedPromptRoleId":"primary"});let original=serde_json::to_string(&base).unwrap();let digest=sha(original.as_bytes());
    let envelope=json!({"schemaVersion":2,"base":base,"originalV1SelectionJson":original,"originalV1SelectionSha256":digest,"migration":{"fromSchemaVersion":1,"serializer":"exact-json-text-sha256","legacySelectionSha256":digest},"extensions":[]});
    let policy:LocalPolicy=serde_json::from_value(json!({"schemaVersion":2,"policyVersion":"native-local-only-v1","policyId":"cpu-policy","projectId":"cpu-project","modelRuleId":"cpu-local-only","nodeId":"1","classType":class,"pythonModule":"cpu-custom-module","nodeSourceSha256":"a".repeat(64),"exactPackageVersion":"cpu-only","workflowSha256":sha(&bytes),"v1SelectionSha256":digest,"bundles":bundles,"requiredEnforcement":{"missingAsset":"fail-before-model-load","download":"forbidden","remoteFallback":"forbidden","externalNetwork":"deny","arbitraryPaths":"forbidden","modelDirectoryWrites":"deny","trustRemoteCode":false,"loras":"disabled","credentials":"preserve-no-export","nativeGuardSha256":"b".repeat(64)}})).unwrap();
    Fixture{root,policy,bytes,envelope}
}
fn inspect(f:&Fixture)->Res<Value>{inspect_policy(&f.policy,&f.bytes,&f.envelope,&[])}
fn mutate_graph(f:&mut Fixture,change:impl FnOnce(&mut Value)){let mut graph:Value=serde_json::from_slice(&f.bytes).unwrap();change(&mut graph);f.bytes=serde_json::to_vec(&graph).unwrap();f.policy.workflow_sha256=sha(&f.bytes);}
#[test]fn exact_local_sdnq_and_all_three_tts_file_policies_are_inspected_without_execution(){for class in ["SDNQSampler","FB_Qwen3TTSCustomVoice","FB_Qwen3TTSVoiceDesign","FB_Qwen3TTSVoiceClone"]{let f=fixture(class);let report=inspect(&f).unwrap();assert_eq!(report["executionAdmission"],false);assert_eq!(report["modelLoads"],0);assert_eq!(report["downloads"],0);assert_eq!(report["directoryWrites"],0);assert_eq!(report["bundles"].as_array().unwrap().len(),f.policy.bundles.len());}}
#[test]fn missing_model_file_fails_before_any_load_without_download(){let f=fixture("SDNQSampler");let path=Path::new(&f.policy.bundles[0].exact_real_path).join("model.safetensors");let extra=f.root.path().join("preserved-model.safetensors");fs::rename(path,extra).unwrap();assert!(inspect(&f).unwrap_err().contains("bundle_missing"));}
#[test]fn exact_full_hash_rejects_same_size_file_changes(){let f=fixture("SDNQSampler");let path=Path::new(&f.policy.bundles[0].exact_real_path).join("model.safetensors");fs::write(path,vec![b'x';f.policy.bundles[0].files[1].bytes as usize]).unwrap();assert!(inspect(&f).unwrap_err().contains("full_hash"));}
#[test]fn unreviewed_extra_file_in_bundle_is_rejected(){let f=fixture("SDNQSampler");fs::write(Path::new(&f.policy.bundles[0].exact_real_path).join("remote-loader.py"),b"CPU only").unwrap();assert!(inspect(&f).unwrap_err().contains("unreviewed_bundle_file"));}
#[test]fn bundles_cannot_use_external_traversal_unc_url_or_device_paths(){for path in ["https://cpu.invalid/model","\\\\server\\model","\\\\?\\C:\\model","C:/cpu/../external","C:/cpu/%MODEL%"]{let mut f=fixture("SDNQSampler");f.policy.bundles[0].exact_real_path=path.into();mutate_graph(&mut f,|g|g["1"]["inputs"]["custom_model_path"]=json!(path));assert!(inspect(&f).is_err());}}
#[test]fn unsafe_pickle_credentials_duplicate_case_or_relative_escape_file_is_rejected(){for name in ["../outside.safetensors","token.json","credentials.json","model.pkl","model.bin","CON.txt",".hf_token","model.safetensors:stream"]{let mut f=fixture("SDNQSampler");f.policy.bundles[0].files[0].relative_path=name.into();assert!(inspect(&f).unwrap_err().contains("unsafe_or_duplicate"));}}
#[test]fn sdnq_requires_false_download_and_exact_local_registered_bundle(){for (field,value) in [("auto_download",json!(true)),("model_selection",json!("remote/model")),("custom_model_path",json!("C:/another/model")),("use_quantized_matmul",json!(true)),("num_frames",json!(2))]{let mut f=fixture("SDNQSampler");mutate_graph(&mut f,|g|g["1"]["inputs"][field]=value);assert!(inspect(&f).is_err());}}
#[test]fn all_five_sdnq_loras_are_disabled_in_selection_path_and_strength(){for i in 1..=5{let prefix=if i==1{"lora".into()}else{format!("lora{i}")};for field in [format!("{prefix}_selection"),format!("{prefix}_custom_path"),format!("{prefix}_strength")]{let mut f=fixture("SDNQSampler");mutate_graph(&mut f,|g|g["1"]["inputs"][field]=json!("unreviewed"));let reason=inspect(&f).unwrap_err();assert!(reason.contains("loras_must_be_disabled")||reason.contains("external_path_forbidden"));}}}
#[test]fn binding_cannot_turn_on_download_override_models_or_add_external_reference(){let f=fixture("SDNQSampler");for field in ["auto_download","custom_model_path","lora_custom_path","model_selection"]{let b:InputBinding=serde_json::from_value(json!({"nodeId":"1","input":field,"value":"unsafe"})).unwrap();assert!(inspect_policy(&f.policy,&f.bytes,&f.envelope,&[b]).unwrap_err().contains("fixed_model_control_override"));}let b:InputBinding=serde_json::from_value(json!({"nodeId":"1","input":"prompt","filePath":"C:/external/reference.wav"})).unwrap();assert!(inspect_policy(&f.policy,&f.bytes,&f.envelope,&[b]).unwrap_err().contains("reference_or_duplicate"));}
#[test]fn tts_requires_exact_model_and_tokenizer_choices(){let mut f=fixture("FB_Qwen3TTSCustomVoice");mutate_graph(&mut f,|g|g["1"]["inputs"]["model_choice"]=json!("0.6B"));assert!(inspect(&f).unwrap_err().contains("exact_model_tokenizer"));let mut f=fixture("FB_Qwen3TTSVoiceClone");f.policy.bundles.pop();assert!(inspect(&f).unwrap_err().contains("exact_model_tokenizer"));}
#[test]fn unreviewed_remote_fallback_and_secret_keys_never_enter_export(){for key in ["repo_id","model_url","api_key"]{let mut f=fixture("FB_Qwen3TTSVoiceDesign");mutate_graph(&mut f,|g|g["1"]["inputs"][key]=json!("CPU fake private data"));let reason=inspect(&f).unwrap_err();assert!(!reason.contains("CPU fake private data"));}}
#[test]fn trusted_project_store_does_not_adopt_uploaded_policy_or_revoked_record(){let f=fixture("SDNQSampler");let value=serde_json::to_value(&f.policy).unwrap();let settings=json!({"entries":{"workflow-native-local-only-policies":{"value":[value]}}});assert!(trusted_policy(&settings,"cpu-policy","cpu-project").is_ok());assert!(trusted_policy(&settings,"cpu-policy","another-project").is_err());assert!(trusted_policy(&json!({"uploaded":value}),"cpu-policy","cpu-project").is_err());assert!(trusted_policy(&json!({"entries":{}}),"cpu-policy","cpu-project").is_err());}
#[test]fn policy_and_explicit_migration_cannot_be_silently_rewritten(){let mut f=fixture("SDNQSampler");f.envelope["migration"]["serializer"]=json!("flattened");assert!(inspect(&f).unwrap_err().contains("explicit_migration"));let mut f=fixture("SDNQSampler");f.policy.required_enforcement.download="allowed".into();assert!(inspect(&f).unwrap_err().contains("required_enforcement"));}
#[test]fn static_checks_never_claim_custom_process_or_loaded_source_guarantees(){let f=fixture("SDNQSampler");let r=inspect(&f).unwrap();assert_eq!(r["executionAdmission"],false);assert!(r["blockers"].as_array().unwrap().iter().any(|v|v.as_str().unwrap().contains("process-enforcement-missing")));let mut p=serde_json::to_value(&f.policy).unwrap();p["uploadedExecutionAdmission"]=json!(true);assert!(serde_json::from_value::<LocalPolicy>(p).is_err());}
#[test]fn hidden_path_or_remote_fallback_controls_cannot_bypass_exact_local_inputs(){for (key,value) in [("tokenizer_path",json!("C:/external")),("cache_dir",json!("C:/external")),("pretrained_model_name_or_path",json!("remote/repo")),("local_files_only",json!(false))]{let mut f=fixture("FB_Qwen3TTSCustomVoice");mutate_graph(&mut f,|g|g["1"]["inputs"][key]=value);assert!(inspect(&f).is_err());}}
